pages/components/alert.njk, scss/_utility.scss, scss/components/_example.scss
- Adding inline image max width and height
- Adjusting inline image styles on alert page
=> Adding inline image size ability, updating alert page

pages/release-notes.njk
Adding design kit v1.8.0 release notes info from 6/14 to Release notes page
=> Adding 1.8.0 release notes to Release notes page

pages/design-code-status.njk
Updates to Design/code status page to reflect current state of design system and PFE
=> Updates to Design/code status page

scss/_utility.scss
Don't need a max width on body text (`p`) anymore
=> Change max width of body text from 750px to 1000px

pages/components/progress-steps.njk, webroot/assets/progress-steps/progress-steps-responsive-desktop.svg, webroot/assets/progress-steps/progress-steps-responsive-mobile.svg, webroot/assets/progress-steps/progress-steps-responsive-tablet.svg
Tweaked some styles and images
=> Cosmetic changes to Progress steps page to align to new Link page

pages/components/progress-steps.njk
Tweaks to Interaction state image sizes
=> Progress steps page image tweaks

js/global.js, pages/development.njk, scss/components/_section.scss
Adding new "Development" page, stemming from https://docs.google.com/document/d/1TYAxGv0ZxMdBL1RAcBB0vFvpJoJWlE2jZwTRJjGLouQ/edit?usp=sharing
=> Adding new development page

pages/foundations/grid.njk, pages/foundations/typography.njk, scss/_utility.scss
=> Adding updates to limit width of text across site, and adding notes about it in documentation

pages/release-notes.njk
- removed XD file links to changes that are on ux.redhat.com
- removed target="_blank"
- removed pagination update under v1.8.0
=> Added v.1.9.0 release notes and updated old release notes

docs/components.njk
Signed-off-by: Adithya Krishna <adikrish@redhat.com>
**Description:**
Fixed skip-nav component link at https://ux.redhat.com/components/
=> [Bug] - Updated skip-nav Link

LICENCE.md
=> chore: add license

docs/_includes/layout-base.njk
=> docs: opt-in to page autoreveal

.gitignore, declaration.d.ts, tsconfig.json
=> chore: fix typescript config

docs/main.css
=> docs: font-size and light-height from rhds

.changeset/rh-alert-initial.md, package.json
1. add a changeset for rh-alert
2. set the publishconfig access to public (since we're scoped)
=> chore: add rh-alert changeset

.github/ISSUE_TEMPLATE/5-migrate-pfe.yml
1. Added issue for for migration PFE-components
1. @markcaron is this good?
=> chore: add pfe-* migration issue form

docs/components/_starter.njk
1. replace insecure content (`http://`) with secure (`https://`)
1. does netlify build pass without warnings?
=> docs: fix insecure mixed content

.github/workflows/release.yml, .husky/pre-commit, package-lock.json, package.json
1. update husky and run its install step
1. checkout this branch on a clean copy of the repo and run npm ci
see #295
=> chore: fix husky dependency

lib/RHDSScreenSizeController.ts
1. add `RHDSScreenSizeController`
as discussed in #278
=> feat: screen size RHDSScreenSizeController

.changeset/wild-bottles-join.md
1. Late addition changeset for #287
=> chore: added changset for PR that was already merged.

.changeset/wild-bottles-join.md
1. add syntax highlighting for the screensize changeset
=> chore: highlight changeset

.github/ISSUE_TEMPLATE/1-new-component.yml, .github/ISSUE_TEMPLATE/2-dev-handoff.yml
1. set @methomps as the default assignee for dev-handoff tickets
=> chore: assign @methomps to dev handoff issue

elements/rh-footer/README.md
1. Updated footer README example for beta.5
=> docs(footer): readme content for beta 5

.changeset/polite-wasps-own.md, package-lock.json, package.json
1. add missing `npm-run-all` dependency (i.e. `run-s` and `run-p`)
2. update dependencies
1. merge this then follow repro in #379
=> 379 unable to install rhdselements

package-lock.json, package.json
1. remove patch-package and postinstall hook
1. merge and repro as #379
=> chore: remove patch-package

.changeset/big-humans-know.md
1. whoopsie... forgot changeset in last pr
=> chore: add changeset

.eleventy.cjs, docs/public/red-hat-outfit.css
andy@outfit.io (previous owners of our netlify site's name) requested to replace this broken link until they are able to update their content.
=> hotfix: replace broken link

.changeset/polite-pets-reflect.md, elements/rh-footer/rh-footer-block.ts, elements/rh-footer/rh-footer-copyright.ts, elements/rh-footer/rh-footer-links.ts, elements/rh-footer/rh-footer-social-link.ts, elements/rh-footer/rh-footer.ts, elements/rh-footer/rh-global-footer.ts
1. map footer's classes to tag names at type level
=> fix(footer): map classes to tag names

.changeset/plenty-tools-mix.md, package-lock.json, package.json
=> chore: add tslib dependency

.changeset/eleven-coats-fix.md, elements/rh-secondary-nav/demo/rh-secondary-nav.html
1.  Fixed path for light dom CSS in secondary-nav demo
=> fix(secondary-nav): lightdom css path 

elements/rh-footer/README.md, elements/rh-footer/demo/rh-footer.html
1. Updated `rh-footer` docs to contain data-analytic recommendations.
=> docs(rh-footer)

elements/rh-secondary-nav/README.md
=> docs(secondary-nav)

elements/rh-stat/README.md
Updating the `rh-stat` component README.md file to contain information about the component.
=> [rh-stat]: Updating README.md file

elements/rh-alert/README.md
Updating the README.md file to contain information about the `rh-alert` component.
=> [rh-alert]: Updating README.md

elements/rh-secondary-nav/demo/analytics.html
This is the demo HTML file with analytics data attributes added. Benny recommended putting this in its own HTML file rather than replacing the original demo file. I followed the structure for data analytics attributes that is being used currently in the main redhat.com nav.
1. Took the original demo HTML file and added analytics data attributes to it. Created a new analytics file in the folder so that users can view the demo code with or without the analytics attributes. 
1. Verify that the data analytic attributes are correct
1. This will need to be looked over by the analytics team to ensure the structure meets their requirements.
=> created analytics.html file

.changeset/tricky-glasses-jam.md
1. revise the initial rh-tooltip changelog
=> docs(tooltip): update changelog

elements/rh-secondary-nav/demo/dark-variant.html
1. update the relative urls in secondary-nav's dark variant demo
1. check the dp, run dev server
=> docs(secondary-nav): update dark demo

.eleventy.cjs, .pfe.config.json, custom-elements-manifest.config.js, docs/components/components.md, package-lock.json, web-dev-server.config.js
1. use .pfe.config.json
Depends on https://github.com/patternfly/patternfly-elements/pull/2112
=> chore: use pfe.config.json

.changeset/rotten-hats-pump.md, elements/rh-alert/demo/demo.css, elements/rh-alert/rh-alert.css, package.json
Fixes issues related to font-family and cursor pointer for rh-alert described https://github.com/RedHat-UX/red-hat-design-system/issues/516
=> fix: rh-alert not using correct font-family, cursor pointer

.changeset/rh-pagination-initial.md
1. update the pagination changelog
1. none
should conform to wiki guidelines
=> chore(pagination): update changelog

docs/foundations/color.njk
1. Updated Danger alert values on Color page per DPO conversations.
=> Updated Danger alert values on Color page per DPO conversations

docs/foundations/grid.njk
1. Updating breakpoints table per token conversations.
=> Updating breakpoints table per token conversations

.changeset/rh-pagination-initial.md
1. Update the pagination changelog with a link to docs
1. none
=> docs(pagination): update changelog

.changeset/thin-lemons-march.md, elements/rh-footer/rh-footer-social-link.ts, elements/rh-footer/test/rh-footer.spec.ts, package-lock.json
1. Update pfe-icon dependency
2. Update rh-footer tests, which depends on pfe-icon's apis 
1. Try this with proxy, I think it's likely to break pages on RHDS, but OTOH, this is blocking [tests which depend on the pfe-icon implementation](https://github.com/RedHat-UX/red-hat-design-system/pull/599/checks?check_run_id=9380088070)
=> fix(footer): icon dep

elements/rh-blockquote/README.md, elements/rh-blockquote/rh-blockquote.css
Fixed the padding/margin to match the [design spec](https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/f5c8e80c-83cb-4ae9-8e92-5991c39e738b/specs/).
Also updated the font-weight, since it seems `regular` is mapped to `300`.
=> Fixing margin and font-weight issues

.changeset/shiny-bats-grab.md, elements/rh-cta/rh-cta.css, elements/rh-cta/rh-cta.ts
1. Made cta's `on` attribute private
1. put cta on different contexts
2. make sure it looks right
3. toggle `on` attr with different values
4. make sure that has no effect
=> fix(cta): make `on` private

.changeset/five-jars-smell.md, lib/context/color.ts
1. Added request to host for an update after  properties changed in `contextConsumer`
=> fix(context): request host for update

.changeset/brave-trees-serve.md, .changeset/fresh-comics-repeat.md, .changeset/fuzzy-rabbits-nail.md, elements/rh-tag/test/rh-tag.spec.ts
1. fix the rh-tag tests, using token names as specified
=> test(tag): use tokens in tests

.changeset/dry-pans-mix.md, .changeset/rare-camels-turn.md
=> docs: update changesets

docs/release-notes.njk
=> Release notes page update

CONTRIBUTING_DEV.md
=> docs: update CONTRIBUTING.md

.changeset/weak-parents-smoke.md, scripts/bundle.js
1. ensure bundle is prepared when publishing
1.
=> fix: bundle in package phase

docs/release-notes.njk
I added two new words to the Release notes page as part of a demo.
=> Update Release notes page

elements/rh-subnav/rh-subnav.ts
1. fix a bad this reference in RhSubnav's static initializer block
1. load up any page with rhds.min.js on it (including homepage)
2. There should be no console errors sourcemapped to `rh-subnav.ts`
=> fix(subnav): this reference

.changeset/thin-paws-call.md, elements/rh-subnav/demo/rh-subnav.html, elements/rh-subnav/demo/rh-subnav.js, elements/rh-subnav/rh-subnav.ts
1. Added updateActiveItem for roving-tab-index controller
Closes #769 
1. View Deploy preview [subnav demo](https://deploy-preview-771--red-hat-design-system.netlify.app/components/subnav/demo/), new Dynamic activation demo should set the correct tabindex when an item is clicked.  
Tabbing through the 3 demos the active item's should all hold the first tab order  `tabindex="0"`.
=> fix(subnav): add updateActiveItem for roving-tab-index controller

.changeset/rh-footer-responsive-header-border.md, elements/rh-footer/rh-footer-responsive.css.ts, elements/rh-footer/rh-footer.css
Closes #791 
1. juggle footer's responsive css
https://deploy-preview-806--red-hat-design-system.netlify.app/elements/footer/demo/
at 992 and greater px wide, border should show under logo with padding between border and links
at 991 px and fewer, no border should show
=> fix(footer): responsive header border

.changeset/remove-brand-red-danger.md, elements/rh-button/rh-button.css, elements/rh-pagination/rh-pagination.css
1.  Updated the token value for `--_danger-background-color` to `#c9190b;`.  
1.
1. This value will be replaced when the token values are created in the `tokens` repo
=> chore: redoing token variables

.changeset/big-humans-know.md, .changeset/clever-moose-invent.md, .changeset/cool-parents-rescue.md, .changeset/dry-pans-mix.md, .changeset/eight-garlics-grow.md, .changeset/eleven-hounds-cry.md, .changeset/fifty-colts-cross.md, .changeset/mean-teachers-smile.md, .changeset/metal-chairs-pay.md, .changeset/rh-secondary-breaking.md, .changeset/selfish-dodos-eat.md, .changeset/short-llamas-hammer.md, .changeset/silver-plums-fold.md, .changeset/slimy-mangos-deliver.md, .changeset/smooth-rats-care.md, .changeset/smooth-rats-cares.md, .changeset/stale-rocks-enjoy.md, .changeset/tame-ducks-raise.md, .changeset/tender-lies-play.md, .changeset/thick-boats-perform.md, .changeset/thin-lemons-march.md, .changeset/tiny-apricots-train.md, .changeset/unlucky-otters-chew.md, .changeset/violet-paws-admire.md, .changeset/weak-parents-smoke.md, .changeset/wet-rocks-yawn.md, package-lock.json, package.json
=> chore: update tokens version

.changeset/pre.json
=> chore: graduate from beta

docs/index.njk
Click "Submit feedback" button at the bottom of the [homepage](https://deploy-preview-918--red-hat-design-system.netlify.app/) and check that links to a "Feedback" section on the "Get Started" page.
Closes #913
=> docs(homepage): update "Submit feedback" link

docs/_plugins/rhds.cjs
Closes #911 
1. assign the componentstatus table csv to each docsPage so renderfile can pick up on it.
=> docs: fix componentStatus tables

.github/workflows/test.yml, docs/scss/_utility.scss, elements/rh-alert/docs/10-style.md, package.json
@coreyvickery, I addressed a couple things from your review of the live Alerts page:
1. Fixed the styles for the notes in the Anatomy section
2. Removed a link break in Interaction States copy
1.
Closes #903
=> docs(alert): edit Alert page

docs/_plugins/rhds.cjs, docs/elements/index.md
1. fix missing titles in the element listing in `/elements/`
=> docs: fix element listing titles

docs/_includes/layout-demo.njk, eleventy.config.cjs
fixes #958
1. add element internals polyfill to demo page layout, import map
1. check out tabs in old safari
=> docs: element internals polyfill

docs/elements/elements.html
=> docs: import alert each time

.changeset/rh-cta-click-link-bg.md, elements/rh-cta/rh-cta.css
Closes #997
Closes #998 
1. :ninja: apply the padding to the slotted link
1. run tests, do visreg manually
=> fix(cta): clickable background

docs/assets/prism.css, docs/foundations/typography.njk, docs/main.css, docs/public/red-hat-outfit.css, docs/release-notes.njk, docs/scss/_base/_normalize.scss, docs/scss/_utility.scss
=> docs: use rh code font

elements/rh-navigation-secondary/docs/00-overview.md
…omponent
1. Reverted change to exampe palette for sample component on overview [age
1.
=> docs(navigation-secondary):  palette light on sample component

docs/scss/_base/_base.scss
1. increase header margin on element docs (100px - (paragraph block margin===18px))
2. apply that margin to h3
=> docs: increase header margin

package.json
@eyevana
1. add @eyevana to the package contributors list. Please edit email address as you wish
=> fix: acknowlege contribution

.changeset/rh-tabs-css-props-cem.md, .changeset/rh-tabs-token-typo.md, .changeset/rh-tooltip-deprecate-bem-props.md
=> docs: fix changesets again

docs/scss/components/_header.scss
Closes #1060
1. make the subnav's container sticky, calculating the height of the whitespace and header
1. check out an elements page in the dp
=> docs: make subnav sticky

elements/rh-avatar/docs/10-style.md, elements/rh-tabs/docs/10-style.md, elements/rh-tabs/docs/20-guidelines.md
Closes #1037 
1. Changed `Variations` to `Variants` and `variations` to `variants` across all element docs
1. Just double check that I spelled everything correctly and that I didn't miss any spots in our docs
=> docs: use consistent terminology

elements/rh-card/docs/20-guidelines.md
=> docs(card): fix guidelines page

elements/rh-dialog/docs/10-style.md
=> docs(dialog): remove heading from style page

elements/rh-audio-player/rh-audio-player.css
=> fix(audio-player): lint css

docs/_plugins/shortcodes/renderInstallation.cjs, elements/rh-audio-player/docs/40-code.md, elements/rh-footer/docs/30-code.md, elements/rh-navigation-secondary/docs/30-code.md, elements/rh-pagination/docs/30-code.md, elements/rh-subnav/docs/30-code.md
1. Added prose clarifying use of `npm install` and `import maps`
2. Added prose about future state CDN
3. Added lightdom block to all components with `-lightdom.css`
1. View [deploy preview](https://deploy-preview-1118--red-hat-design-system.netlify.app/)
=> docs: render installation prose

elements/rh-tag/docs/10-style.md
#1124 
1. Updated the `Light Theme` and `Dark Theme` headings to read `... theme`
=> docs(tag): minor style page edits

.changeset/little-mice-work.md, elements/rh-tabs/rh-tab.css
1. Fixed vertical tabs, tab text alignment when long text is present and flex centers the text.
Closes #1195 
1. View deploy preview
=> fix(tabs): vertical tabs text alignment

.changeset/many-apes-relax.md, elements/rh-cta/demo/color-context.html, elements/rh-cta/rh-cta.ts, lib/context/color/consumer.ts, lib/context/color/controller.ts, lib/elements/rh-context-provider/test/rh-context-provider.spec.ts, package.json
1. remove context provider from cta
2. make context consumers register after first update
1. check all the context integrations (nav, accordion come to mind)
=> fix(cta): context

.changeset/strong-pens-boil.md
1. Updated changeset to match previously released feature (code block)
=> docs(rh-timestamp): update changeset

docs/_plugins/shortcodes/feedback.cjs, docs/about/roadmap.md, docs/release-notes.md, docs/scss/styles.scss
1. Added Roadmap page under About
2. Moved shared styles out of Release Notes into Styles.scss
3. Cleaned up Roadmap and Release Notes feedback sections
=> Adding roadmap page and aligning shared styles with release notes

.changeset/rh-tabs-expand-event-doc.md, elements/rh-tabs/rh-tab.ts
1. fix the jsdoc for the `expand` event in tabs
=> fix(tabs): event docs for rh-tab

docs/foundations/spacing.njk, elements/rh-card/docs/10-style.md, elements/rh-jump-links/docs/10-style.md, elements/rh-popover/docs/10-style.md, elements/rh-progress-steps/docs/10-style.md, package-lock.json
Removed references to PF4 spaces and replaced them—where possible—with our RH tokens table of spacers. Still need to get better images/screenshots at some point.
Please double check:
- Accuracy of available spacer values
- Code quality
- Text/copy/typos
=> docs: removing pf spacer references

docs/_plugins/shortcodes/renderInstallation.cjs, elements/rh-accordion/docs/30-code.md, elements/rh-alert/docs/30-code.md, elements/rh-audio-player/docs/40-code.md, elements/rh-avatar/docs/30-code.md, elements/rh-badge/docs/30-code.md, elements/rh-blockquote/docs/30-code.md, elements/rh-button/docs/30-code.md, elements/rh-card/docs/30-code.md, elements/rh-code-block/docs/40-code.md, elements/rh-cta/docs/30-code.md, elements/rh-dialog/docs/30-code.md, elements/rh-footer/docs/30-code.md, elements/rh-navigation-secondary/docs/30-code.md, elements/rh-pagination/docs/30-code.md, elements/rh-spinner/docs/30-code.md, elements/rh-stat/docs/30-code.md, elements/rh-subnav/docs/30-code.md, elements/rh-tabs/docs/30-code.md, elements/rh-tag/docs/30-code.md, elements/rh-timestamp/docs/30-code.md, elements/rh-tooltip/docs/30-code.md
1.  Updated the render install function to change the name so there is not a conflict with the pf tools render installation function
1.
=> docs: decouple from patternfly tools

.changeset/color-palette-spinner.md, .changeset/spinner-remove-base.md, elements/rh-spinner/rh-spinner.ts
Closes #1280 
1. remove basespinner
2. deprecate colorPalette on spinner (cc @marionnegp )
1. compare dp to prod  demos
=> fix(spinner): remove basespinner

.gitignore, docs/_plugins/importMap.cjs, eleventy.config.cjs
1. Cache 11ty import map between builds
=> perf: speed up docs builds

docs/scss/_utility.scss
1. Fixed back-to-top link blocking right aligned buttons and links
1.
=> docs: fix back-to-top blocking right aligned buttons and links

elements/rh-card/demo/variants.html
1. Add missing alt tag to img in demo
1.
=> docs(card): add missing alt tag

docs/_includes/layout-base.njk, docs/_includes/layout-demo.njk, docs/_plugins/importMap.cjs, eleventy.config.cjs, spandx.config.cjs
Hopefully this is easier to understand and maintain
Depends on #1307
1. clean up importMap code, replacing several truly awful hacks with a smaller number of merely gross hacks.
1. pages, demos, playgrounds
=> docs: simplify import map generation

.changeset/paginator-numeric-part.md, elements/rh-pagination/demo/no-numeric-control.html, elements/rh-pagination/rh-pagination.ts
1. add a `numeric` part to the paginator
1. check the dp https://deploy-preview-1338--red-hat-design-system.netlify.app/elements/pagination/demo/no-numeric-control/
See #1298
=> feat(pagination): add numeric part

.changeset/six-dancers-repair.md, elements/rh-navigation-secondary/demo/analytics.html, elements/rh-navigation-secondary/demo/current-page-indicator.html, elements/rh-navigation-secondary/demo/dark-variant.html, elements/rh-navigation-secondary/demo/deprecated.html, elements/rh-navigation-secondary/demo/long-logo-text.html, elements/rh-navigation-secondary/demo/proxy.html, elements/rh-navigation-secondary/demo/rh-navigation-secondary.html, elements/rh-navigation-secondary/demo/translation.html, elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.css, elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css, elements/rh-navigation-secondary/rh-navigation-secondary.css
1.  Add current page indicator to logo slot 
2. Fixed border values with tokens
3. Fixed duplicate border-block-end in dark variant mobile view.
1.
=> fix(navigation-secondary): add current page indicator to logo

elements/rh-card/rh-card.css
1. fix a bad css merge in card
=> fix(card): bad merge

docs/foundations/color/accessibility.md, docs/foundations/color/index.md, docs/foundations/color/usage.md
Updated the Color page
1. View Color page in[ DP](https://deploy-preview-1357--red-hat-design-system.netlify.app/foundations/color/)
=> feat: change "primitive" to "crayon" or "crayon colors" 

.changeset/tile-flex-blockwise.md, elements/rh-tile/demo/color-context.html, elements/rh-tile/demo/full-width-images.html, elements/rh-tile/demo/tile-group-disabled.html, elements/rh-tile/demo/tile-group-flex.html, elements/rh-tile/demo/tile-group-radio-disabled.html, elements/rh-tile/demo/tile-group-radio.html, elements/rh-tile/demo/tile-group.html, elements/rh-tile/rh-tile.css
Fixes #1359 
1. make tile internal containers grow in the cross-axis, so that the host can flex as well. Make the host a flex container
1. compare *all* the DP demos to production
=> fix(tile): grow tiles along cross-axis 

.changeset/alert-button-link.md
1. fix broken changeset (thus unblocking release)
=> docs: fix broken changeset

.changeset/color-page-update.md
1. Removed [changeset](https://github.com/RedHat-UX/red-hat-design-system/commit/c03a896993dc7efff906f51b215850025afd1079)
1.
=> fix: remove color page changeset

.changeset/alert-fix-inline.md, .changeset/dark-baths-allow.md, .changeset/free-hats-wave.md, elements/rh-alert/demo/inline.html, elements/rh-alert/rh-alert.css, elements/rh-alert/rh-alert.ts
1. fix various issues with rh-alert (see changeset)
2. cherry-picked those fixes from the #1350 for ease of review
=> fix(alert): various fixes

.changeset/code-block-prism.md, elements/rh-code-block/rh-code-block.css
1. fix various issues with rh-code-block (see changeset)
2. cherry-picked those fixes from the #1350 for ease of review
=> fix(code-block): allow slotted prism-highlighted code

.changeset/hungry-experts-design.md, elements/rh-footer/demo/rh-footer.html, elements/rh-footer/rh-footer-social-link.css, elements/rh-footer/rh-footer-social-link.ts
1. Replaces twitter icon with X icon as SVG
Closes #1387 
1.
=> fix(footer): replace twitter with X icon as svg

.changeset/seven-rocks-drop.md, elements/rh-table/rh-table.css
1. Removed css height rule
Closes  #1370 
1.
=> fix(table): remove css positioning and height

.changeset/calm-fishes-sleep.md, elements/rh-table/demo/color-context.html, elements/rh-table/rh-sort-button.css, elements/rh-table/rh-sort-button.ts, elements/rh-table/rh-table-lightdom.css, elements/rh-table/rh-table.css, elements/rh-table/rh-table.ts
1. Adds support for color context 
2. Adds color context demo
Closes #1371 
1. View the [color-context demo](https://deploy-preview-1373--red-hat-design-system.netlify.app/elements/table/demo/color-context/)
Double check that the color combinations paas WCAG accessibility guidelines
=> feat(table): color context support

.changeset/itchy-lands-design.md, elements/rh-dialog/rh-dialog.css, elements/rh-dialog/rh-dialog.ts
=> fix(dialog): remove pfe dependency

.changeset/rotten-oranges-count.md, elements/rh-table/rh-table-lightdom.css, elements/rh-table/rh-table.css, elements/rh-table/rh-table.ts
1. Improved styles for color context, removing inaccurate lightdom styles to apply parent set color-palette.
Closes  #1405
1.
=> fix(table): improve styles for color context

docs/patterns/card/index.md
Closes #1402 
1. import card and surface to the card pattern page
=> docs: import card definition on card page

.changeset/stupid-drinks-own.md, elements/rh-accordion/rh-accordion-header.css, elements/rh-accordion/rh-accordion.css
1.  Updated accordion CSS to include the correct border colors for dark mode, accordion header should now be pulling in the correct variables
1.
=> fix(accordion): CSS is now pulling in correct borders for dark mode

.changeset/empty-birds-film.md, elements/rh-table/demo/row-and-column-headers.html, elements/rh-table/rh-table-lightdom.css
1. Improved mobile styles when `th` has a `data-label` attr in the `tbody`
Improves upon #1288
1.
=> fix(table): mobile th:before styles

.changeset/seven-rocks-drop.md
1. Removed typo from changeset
1.
=> chore(table): fix typo in changeset

docs/release-notes.md
=> Updating v1.3 release notes

.changeset/sixty-lemons-smoke.md, elements/rh-table/rh-table-lightdom.css, elements/rh-table/rh-table.ts
1.  Correctly implemented fallbacks for public api css props, added to cem docs, renamed and deprecated old var name.
Closes #1454 
1.
=> fix(table): custom background hover colors

docs/accessibility/content.md, docs/accessibility/development.md, docs/accessibility/index.md, docs/accessibility/q-a-testing.md
=> Adding rh-code-block and rh-blockquote to accessibility docs

.changeset/empty-suns-sip.md, elements/rh-tile/demo/icon.html, elements/rh-tile/rh-tile.ts
1. Fixed template logic to correctly display slotted content when the icon attribute is undefined.
Closes #1503 
1. View deploy preview icon demo
=> fix(tile): correct icon slot visibility

docs/_includes/component/header.njk, docs/accessibility/content.md, docs/accessibility/resources.md
Updates to Accessibility docs:
1. Added Resources page and included it in side navigation.
2. Added Audio/video section to Content page.
1. Review [Resources](https://deploy-preview-1506--red-hat-design-system.netlify.app/accessibility/resources/) page in DP.
2. Review [Audio/video](https://deploy-preview-1506--red-hat-design-system.netlify.app/accessibility/content/#audio%2Fvideo) section to Content page in DP.
=> docs: accessibility finish pages sections content

elements/rh-tag/demo/color-context.html, elements/rh-tag/demo/filled-color-with-icon.html, elements/rh-tag/demo/outline-with-icon.html
=> docs(tag): fix broken icons

docs/_includes/component/header.njk
1. Removed usersnap js from header.njk
Closes #1509 
1.
=> docs: remove usersnap

package.json
1. use wireit's file cache to hopefully prevent failures like https://github.com/RedHat-UX/red-hat-design-system/actions/runs/8988133555/job/24688276034
=> chore: attempt to make builds less flakey

.changeset/shy-houses-arrive.md, elements/rh-card/demo/variants.html, elements/rh-card/rh-card.css, elements/rh-card/test/rh-card.spec.ts
1. set heading font for card
2. change the html and css for the 'image header with text heading' example in the variants.html demo file
How will this affect localized pages?
=> fix(card): header font

.changeset/wet-feet-pull.md, elements/rh-card/rh-card.ts
Closes #1233 
1. remove article, header, and footer from card
=> fix(card): remove landmarks

.changeset/curly-ways-march.md, package.json
Closes #1562
1. unwhoopsie the react wrappers
```
npm run build
npm pack
```
inspect the newly minted tarball, ensure wrappers exist
=> fix: ship react wrappers

package-lock.json, package.json
1. install esbuild's linux binaries
=> chore: install esbuild for linux

.changeset/tough-pens-brake.md, elements/rh-tag/rh-tag.css
1. Add font-family to styles
Closes #1331 
1. View demo and doc pages 
confirm page font-style doesn't leak
=> fix(tag): font inheritance

.changeset/cuddly-cameras-rhyme.md, elements/rh-tabs/demo/color-context.html, elements/rh-tabs/rh-tab.css, elements/rh-tabs/rh-tab.ts, elements/rh-tabs/rh-tabs.css, elements/rh-tabs/test/rh-tabs.spec.ts
1. Corrects nested controls for `<rh-tab>`.  No longer embeds a `<button>` element.  This same fix was made upstream prior in `pf-tabs`.
Closes #1585
1. View [deploy preview docs demo](https://deploy-preview-1603--red-hat-design-system.netlify.app/elements/tabs/demo/)
Check automated accessibility tests no longer fail on nested interactive controls.
=> fix(tabs): fix nested interactive controls

docs/tokens/tokens.html
1. Tightened up the padding on the `Color function variants` in the [Color tokens tables](https://ux.redhat.com/tokens/color/#color-blue)
1. Check style of the color disclosure and padding around the `Color function variants` in the [Color tokens tables](https://ux.redhat.com/tokens/color/#color-blue)
=> docs: tokens tables layout

.changeset/new-shirts-watch.md, package-lock.json, package.json
Closes https://github.com/jspm/project/issues/337
1. fix another syntax error in react wrappers
=> fix(react): wrapper syntax error

.changeset/few-buckets-cross.md, elements/rh-cta/rh-cta.ts
1. lazy load the `pf-icon` dep in cta
=> perf(cta): lazy-load icon dependency

docs/_includes/layouts/pages/basic.njk, docs/index.njk, docs/styles/grid.css, docs/styles/pages/home.css
1. Fixed heading alignment and size in get started cards on homepage
Closes #1599 
1. View [deploy preview](https://deploy-preview-1601--red-hat-design-system.netlify.app)https://deploy-preview-1601--red-hat-design-system.netlify.app/
=> docs: fix size and heading alignment in get started cards on homepage

.gitignore, package.json
1. fix my prior gitignore oopsie
=> chore: fix the gitignore

elements/rh-popover/docs/00-overview.md
1. Added a "Coming soon" section to the top of the docs overview.
1. Go to the [DP popover page](https://deploy-preview-1695--red-hat-design-system.netlify.app/elements/popover/).
2. Verify that it has a "Coming soon" section with info that the element is not yet available.
=> docs: added coming soon section to popover docs

elements/rh-tile/demo/custom-props.html, elements/rh-tile/rh-tile-lightdom.css, elements/rh-tile/rh-tile.css, elements/rh-tile/rh-tile.ts
1. Fixed `--rh-tile-border-color` custom prop (and all other public custom props) inheritance
1. Go to [Custom Props demo page](https://deploy-preview-1685--red-hat-design-system.netlify.app/elements/tile/demos)
2. Test out overriding the different public [CSS custom properties listed](https://deploy-preview-1685--red-hat-design-system.netlify.app/elements/tile/code/#rh-tile) in the docs
3. Read explanation on accessibility issues and preferred use of theming in [CSS custom properties table](https://deploy-preview-1685--red-hat-design-system.netlify.app/elements/tile/code/#rh-tile)
Closes: #1680
=> fix(tile): css custom properties

elements/rh-progress-steps/docs/00-overview.md
1. Added the same "Coming soon" messaging to Progress Steps' Overview page as we added to Popover's.
1. Checkout and proofread the Coming Soon messaging
=> docs(progress steps): adding coming soon messaging

docs/get-started/developers/tokens.md, docs/get-started/developers/usage.md, docs/styles/styles.css
1. Fixed the code blocks on the Usage and Tokens pages under Get Started —> Developers
1. Go to the deploy preview's Usage and Tokens subpages under Get Started —> Developers
2. Compare to the live versions
3. Double-check accuracy of code blocks and content
=> docs(devs-start): fixing usage and tokens code blocks

.changeset/odd-bugs-repair.md, elements/rh-alert/rh-alert.ts
1. Remove the boolean toast attribute
1.
=> fix(toast): remove boolean toast attribute

docs/elements/demos.html
1. add a fullscreen toggle button to demos
1. can't be really effectively tested until after pfe-4 and rh-icon land
=> docs: fullscreen for demos

.changeset/breezy-turkeys-clean.md, elements/rh-footer/rh-footer.ts
1.  Remove deprecated global slot
Closes #1751 
1.
=> fix(footer): remove deprecated global slot

.changeset/many-foxes-invent.md, elements/rh-spinner/rh-spinner.ts
1. Removed deprecated `color-palette` property
Closes #1753 
1.
=> fix(spinner): remove deprecated `color-palette`

.changeset/cyan-dragons-care.md, elements/rh-cta/rh-cta.ts
1. Removed deprecated public getter
Closes #1750 
1.
=> fix(cta): remove deprecated public getter

docs/styles/fonts.css
1. Fixed the missed font path
1.
=> docs: fix missed font path

elements/rh-footer/rh-footer-lightdom.css
1. Fixed some linting errors in `rh-footer-lightdom.css` that are visible across a few different PRs.
1. You can either a) checkout this branch and run `npm run lint` or b) make sure there are all green checkmarks at the bottom of this PR under "Test / Web Test Runner (pull_request)"
=> fix(footer): linting errors in footer lightdom CSS file

docs/_data/repoStatus.yaml, docs/_plugins/shortcodes/renderInstallation.cjs
1. Updated new statuses
2. Removed duplicate Skip Link element from `repoStatus.yml`
1. Check Design/code status page
=> docs: repo status dupes

.changeset/curvy-ducks-study.md, .changeset/eleven-ligers-share.md, .changeset/good-planets-yell.md, .changeset/metal-snakes-wave.md, .changeset/mighty-vans-dress.md, .changeset/nice-kangaroos-kiss.md, .changeset/serious-lemons-divide.md
1. Further updated and refined the changesets according to feedback from Benny and Mark
1. Read through the Files Changed, make sure each changeset looks okay.
2. If so, approve this PR and we can re-check the prepare release PR. 
Home stretch! 🤞
=> chore: fix changesets v2

package-lock.json, package.json
1. add [patch package](https://npm.im/patch-package) to devdeps
prevents errors on fresh install
1. clone repo to fresh directory
2. `npm i`
=> chore: add patch-package to devdeps

.github/workflows/gh-pages.yml, .github/workflows/gzip.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/validate-pr.yml, docs/assets/javascript/elements/uxdot-toc.css, docs/styles/pages/backpage.css, docs/styles/styles.css, package.json
1. unstick the toc
2. stick the toc on wide screens (brand new sentence?)
=> docs: sticky toc

.changeset/whole-pillows-run.md, elements/rh-back-to-top/rh-back-to-top.css, elements/rh-back-to-top/rh-back-to-top.ts
1. apply the [guidelines](https://ux.redhat.com/elements/back-to-top/guidelines/) to back-to-top
2. remove the (undocumented, and bad for l10n) position css props
=> fix(back-to-top): position

docs/assets/javascript/elements/uxdot-sidenav.css
1. fixes background surface for sidenav. without the fix, it's transparent below the fold
2. makes sidenav vertically scrollable
=> docs: sidenav height and scrolling

docs/assets/javascript/elements/uxdot-sidenav.ts
1. Remove RTI from sidenav, split off from https://github.com/RedHat-UX/red-hat-design-system/pull/1821
1.
=> docs: remove rti from sidenav

.changeset/slimy-experts-call.md, elements/rh-cta/rh-cta.ts
1. Corrected icon not loading on default variant when no icon attr is present.
Closes #1832 
1. [View Deploy Preview](https://deploy-preview-1835--red-hat-design-system.netlify.app/elements/call-to-action/demo/)
=> fix(cta): ensure icon loads on default variant

.changeset/wicked-steaks-love.md, elements/rh-tooltip/rh-tooltip.css, lib/elements/rh-context-picker/rh-context-picker.css
1. Added border radius
2. Use logical properties for positioning
3. Removed deprecated custom CSS properties
Closes #1840 
1.
=> fix(tooltip): add border radius

.gitignore, docs/assets/javascript/elements/uxdot-example.css, docs/assets/javascript/elements/uxdot-example.ts
1. Reinstate `uxdot-example`.
Closes #1847
1.
=> docs: reinstate uxdot-example

docs/foundations/color/index.md
Closes #1757
1. add a grid of color tokens to the [color page](https://deploy-preview-1866--red-hat-design-system.netlify.app/foundations/color/#color-tokens)
Would it be helpful for designers to design in browser on this PR?
=> docs: tokens on color page

docs/assets/javascript/elements/uxdot-pattern.js, package.json
1. Reinstate `uxdot-pattern`
Closes #1848
1.
=> docs: reinstate uxdot-pattern

docs/styles/demo/dev-server.css
1. Removes unused prism.css from dev-server.css
1.
=> docs: remove prism css from dev-server.css

.changeset/big-glasses-drum.md, elements/rh-audio-player/rh-audio-player.ts
1.  Corrected Focus on menu button after escape pressed
Closes #1764 
1.
=> fix(audio-player) corrected focused on menu button after escape pressed

elements/rh-cta/rh-cta.css, elements/rh-cta/rh-cta.ts
Closes #1872 
1. restores default colors to cta
2. fixes arrow spacing
=> fix(cta): restore color and spacing

.changeset/mean-months-laugh.md, elements/rh-alert/rh-alert.css, elements/rh-alert/rh-alert.ts
Fixes #1530
1. hide the alert header when empty
=> fix(alert): hide empty header

docs/_plugins/shortcodes/renderCodeDocs.cjs, docs/_plugins/tokensHelpers.cjs
1. fix white space on elements code pages
=> docs: fix whitespace and markdown rendering in tables

.changeset/honest-icons-itch.md, .changeset/large-geese-suffer.md, elements/rh-tabs/demo/icons-and-text.html, elements/rh-tabs/rh-tab-panel.css, elements/rh-tabs/rh-tab-panel.ts, elements/rh-tabs/rh-tab.css, elements/rh-tabs/rh-tabs.css, elements/rh-tabs/rh-tabs.ts, elements/rh-tabs/test/rh-tabs.spec.ts, package-lock.json, package.json
1. Corrected interaction state styles
2. Nested CSS to clean up complexity of styles
3. Fixed padding issues in panel introduced after prop drilling was remove and context added, added context to panel.
4. Removed styling based off :host attributes converted to all shadow classes
5. Fixed couple non logical properties
6. Converted from `@media` based queries to `@container`
Closes #1886 
1.  View [Deploy Preview](https://deploy-preview-1904--red-hat-design-system.netlify.app/elements/tabs/demo/color-context/) 
Please, look at the styles closely to ensure that they match expectations, this ended up being a fairly large refactor of the styles in order to introduce nesting.  The CSS was complex prior, and this refactor was much needed and now is much more readable and understandable (IMHO …
=> fix(tabs): interaction states, css refactor/nesting

docs/assets/javascript/elements/uxdot-header.css, docs/assets/javascript/elements/uxdot-header.ts
1.  Refactored `uxdot-header` css, nested easier to read
2. Fixed the weird positioning causing horizontal scrollbars in certain occasions
Closes #1923
1. View Deploy Preview
=> docs: fix header element causing horizontal scroll bars

docs/release-notes/index.md
1. Added version 2.1.0 release notes
2. Used the `compact` tag size for the tables
1. Check accuracy of the release notes table
=> docs: Clefairy release notes

docs/theming/color-palettes.md, docs/theming/patterns/collage.html
1. Fixed missing tab-panels 
2. Added mobile friendly styles.
1.
=> docs: fix tabs missing panels, add mobile friendly styles

docs/_includes/partials/component/sidenav.njk
1. Made the `Planned` tags in the sidenav compact.
1. Check everything looks ok.
=> docs: making planned tags in sidenav compact

.changeset/new-years-pull.md, elements/rh-tabs/rh-tab.ts
1. corrected active tab styles in SSR
1.
=> fix(tabs): corrects active tab styles in SSR

docs/patterns/card/examples.md, docs/patterns/card/patterns/accented.html, elements/rh-card/docs/20-guidelines.md
1. Added accented pattern to `<rh-card>`
1. Review [Card Guidelines pattern tiles](https://deploy-preview-2024--red-hat-design-system.netlify.app/elements/card/guidelines/#patterns).
2. Click on the "Accented" tile.
3. Review [Accented card pattern](https://deploy-preview-2024--red-hat-design-system.netlify.app/patterns/card/examples/#accented-cards) and code.
=> docs(cards): Add `<rh-card>` accented pattern

.changeset/twelve-cups-yawn.md, elements/rh-button/rh-button.ts
1.  Applied `aria-disabled` to internals if button is disabled
Closes #2041 
1. Test button using [form control demo](https://deploy-preview-2042--red-hat-design-system.netlify.app/elements/button/demo/form-control/)
=> fix(button): aria disabled button

package-lock.json, package.json
they were erroneously added to main deps at some point
1. move dev deps out of prod deps
Thanks to @KamiQuasi for helping me spot this
=> chore: move dev deps out of prod deps

docs/theming/developers/developers.md
1. elaborate on how to write bimodal SVG
=> docs: elaborate on bimodal svg 

docs/accessibility/content.md
=> docs: trailing script

docs/_includes/partials/component/footer.njk
1. Updated site footer
1. Check to see if the footer looks right
=> docs: update site footer

docs/accessibility/index.md
1. Reorganized the page's content.
1. [Check the updated page](https://deploy-preview-2266--red-hat-design-system.netlify.app/accessibility/) and ensure that the new structure and text matches our content review.
=> docs: update a11y > fundamentals per content review

elements/rh-blockquote/docs/20-guidelines.md
1. Updated the Guidelines page of rh-blockquote with some prose we missed from #2258. 
1. Visit the [Guidelines page in the DP](https://deploy-preview-2267--red-hat-design-system.netlify.app/elements/blockquote/guidelines/).
2. Make sure the paragraph under "General usage" matches the content in the [Figma prototype](https://www.figma.com/proto/bEPvrDAOBjHCH6C05GRgMt/Element---Blockquote-updates?node-id=1-92&p=f&t=CwxGpXjg5YXwCVp5-0&scaling=scale-down&content-scaling=fixed&page-id=1%3A4).
Super tiny edit here.
=> docs(blockquote): updated guidelines prose

docs/release-notes/index.md
1. Updated release notes.
1. Check 3.0 release notes
2. Check 2.1.1 and 2.1.2 patch changes below 3.0
=> docs(release-notes): updating 3.0 release notes

docs/_plugins/rhds.ts, docs/get-started/designers/faqs.md, docs/get-started/designers/figma-library.md, docs/get-started/designers/github.md, docs/get-started/designers/index.md
1. Improved the IA of the [Get Started: Designers section](https://deploy-preview-2239--red-hat-design-system.netlify.app/get-started/designers/)
2. Add subnav and subpages for each "section" within Designers
3. Updated the columns under `Learn about our design system`, adding `<rh-tile>`s for each
1. Checkout the [Get Started: Designers section](https://deploy-preview-2239--red-hat-design-system.netlify.app/get-started/designers/) in the deploy preview
2. Proof read
3. Check code
=> docs(designers): improving IA of the Designers Get Started section

docs/styles/demo/styles.css
1. add color scheme support to demos
1. look at any element's /demos/ page.
2. toggle page color scheme with the header toggle
2. open a demo in it's own tab
3. toggle device color scheme
=> docs: make demos obey color scheme pref

.github/workflows/gh-pages.yml, .github/workflows/release.yml, .github/workflows/test.yml
1. Updated github wireit workflows to use the v2 API caching
1.
=> chore: update workflows to use v2 caching

elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts, elements/rh-subnav/rh-subnav.ts, package-lock.json, package.json
1. update slotcontroller dep
2. fix elements affected by double-update issue there, update tests
=> chore: update deps

docs/foundations/interactions/links/index.md
Added alert about Figma styles in the ["Interaction states" section](https://deploy-preview-2328--red-hat-design-system.netlify.app/foundations/interactions/links/#interaction-states) of Interactions > Links.
1.
=> docs(interactions - links): add alert about Figma text styles

docs/foundations/typography/scale-and-rhythm/index.md
Updated some language here and there, no breaking changes to token values.
=> [docs] Scale and rhythm page minor edits

.changeset/red-steaks-sink.md, elements/rh-navigation-primary/rh-navigation-primary-item.css
1. Corrected the style of the cursor for secondary dropdown
1.  View the deploy preview hover over a secondary dropdown
=> fix(navigation-primary): secondary dropdown cursor style

.changeset/bitter-times-retire.md, elements/rh-tooltip/rh-tooltip.ts
1. do a better job of calculating text content when announcing with the tooltip.
1. see code block and tooltip demos. codeblock in particular see in #2389
=> fix(tooltip): better sr support

docs/patterns/tabs/examples.md, eleventy.config.ts, uxdot/uxdot-pattern.css, uxdot/uxdot-pattern.ts
1. Fixed `<uxdot-pattern>` so that it displays the content slotted into the default slot.
**Before:**
<hr>
**After:**
1. First, note the Patterns > Tile > [Examples](https://ux.redhat.com/patterns/tile/examples/) page on uxdot.
2. If you right click > Inspect element, you'll notice that there is default content slotted into `<uxdot-pattern>`; however, it does not display on screen.
3. Now if you look at [the same page](https://deploy-preview-2588--red-hat-design-system.netlify.app/patterns/tile/examples/) in the DP, notice how that content is visible.
4. Also note the "Tile with tag" example below it does not have content slotted into the default slot. Verify the spacing looks correct.
5. Verify other `<uxdot-pattern>` elements look okay on other Patterns pages.
6. Verify …
=> docs(uxdot-pattern): show content in description slot

uxdot/uxdot-sidenav.css
1. uxdot-sidenav should only vertically scroll if overflowed
1.
=> docs: correct sidenav auto scroll
