RedHat-UX/red-hat-design-system

- webroot/CNAME
I believe this will fix an issue where the custom domain gets removed on publish to Github Pages.
Per the [docs](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages):
> For your site to render at the correct domain, make sure your CNAME file still exists in the repository. For example, many static site generators force push to your repository, which can overwrite the CNAME file that was added to your repository when you configured your custom domain. If you build your site locally and push generated files to GitHub, make sure to pull the commit that added the CNAME file to your local repository first, so the file will be included in the build.
When you manually add the custom domain to the GH page settings it …
> Adds CNAME file to preserve custom domain setting

- .eleventy.cjs
- package-lock.json
- package.json
- scripts/build.js
- tsconfig.json
1. disables bundle minification due to a [bug in
`minify-html-literals`](https://github.com/asyncLiz/minify-html-literals/issues/37)
2. uses [new APIs in `@patternfly/pfe-tools/esbuild.js`](https://github.com/patternfly/patternfly-elements/pull/2030) to bundle PFE and RHDS for the docs site
NB: once PFE components are done porting over, we'll remove the
pfe.min.js altogether, and use exclusively `<rh-*` elements in the
docs site
1. see https://github.com/patternfly/patternfly-elements/pull/2030
https://github.com/patternfly/patternfly-elements/pull/2030 must merge and release first before testing this
> chore: update build script

- package-lock.json
- package.json
- spandx.config.cjs
1. Adding [spandx](https://github.com/redhataccess/spandx) config for RHDC.  This will allow us to proxy RHDC and other properties while developing/testing our components.
2. Added `/proxy/index.html` that is injected into the bottom of the page via the proxy.  This means that all content contained in this file will be present in the source html on page load.
3. Any request to a file at `/elements/` will be proxied to `web-dev-server`
1.  Start the dev server `npm run dev`. Ensure it's running on port `8000`
2. In a separate window start the proxy `npm run proxy`
3. Open the url from the proxy server. (typically http://localhost:8001/en)
4. You should see the RHDC homepage.
5. Scroll all the way to the bottom, you should see the new `rh-footer`
> tools(proxy): adding Spandx configuration to proxy RHDC while developing

- .changeset/cold-ravens-develop.md
- elements/rh-footer/demo/proxy.html
- elements/rh-footer/demo/rh-footer.html
- elements/rh-footer/rh-footer-block.css
- elements/rh-footer/rh-footer-lightdom.css
- elements/rh-footer/rh-footer.css
1. Ported styles from `@patternfly/pfe-styles/pfe-base.css`.  `pfe-base.css` has a mixed bag of styles that have negative consequences.
2. This is a branch off of #302 
1. Start dev server `npm run dev`
3. Start the proxy server in a separate process `npm run proxy`
4. Open the the proxy url http://localhost:8001
5. Scroll to the bottom and you should see the rh-footer in context of the RHDC site.
6. Ensure it matches the footer in the dev server http://localhost:8000/demo/rh-footer/
> fix(footer): fix styles when used on redhat.com

- .changeset/metal-ants-mate.md
- elements/rh-footer/RhFooter.ts
- elements/rh-footer/rh-footer-lightdom.css
1. Fixed #307 
2. Fixed the social-links slot to not override the social-links internal `rh-footer-links`
3. Fixed the social-links hrefs to point to the default RHDC links
1. checkout `fix/rh-footer/dev-handoff-fixes` branch
2. `npm run dev`
3. Visit http://localhost:8000/demo/rh-footer/
4. Verify that the `<a>` tags in the footer are correctly styled with the dark theme colors
5. Verify that the social links slot works correctly by editing with the following code `elements/rh-footer/demo/rh-footer.html`:
```html
<rh-footer-social-link slot="social-links" icon="web-icon-github">
<a aria-label="Github" href="#github">Github</a>
</rh-footer-social-link>
<rh-footer-social-link slot="social-links" icon="web-icon-github">
<a aria-label="Github" href="#github">Github</a> …
```
> fix(footer): dev handoff fixes

- docs/get-started.njk
- docs/get-started/design-system-kit.njk
- docs/get-started/fts-starter-kit.njk
- docs/get-started/icon-library.njk
- docs/get-started/logo-library.njk
Fixes #344
1. replace all instances of service-now urls (they were all the same) with the VPN link mark generated.
> docs: remove internal urls

- elements/rh-dialog/rh-dialog.css
1. In Chrome and Safari there the video iframe wasn't expanding the full width of the dialog.
2. Added a calculation that prevents the video player from overflowing off the bottom of the screen.  Accounts for max-hight of the viewport and aspect ratio.
3. I noticed that there was an occasional 1px discrepancy between the dialog and the container of the video player so I added a 1px buffer so you don't see the background of the dialog bleed through.
1. Visit `http://localhost:8000/demo/rh-dialog/` in Chrome or Safari
2. Open the video dialog example
3. Resize your browser between different aspect ratios to ensure the video player is completely visible at all times.
> fix: Feat/dialog mp video fixes

- elements/rh-footer/rh-global-footer.ts
when `@customElement` or `customElements.define` is used, there's no need for the `@element` jsdoc tag, and in fact, leaving this here corrupts the manifest.
> fix(footer): manifest for global footer

- .changeset/cool-parents-rescue.md
- .eleventy.cjs
- .gitignore
- package-lock.json
- package.json
- scripts/bundle.js
- scripts/transform-css.js
- transformers/css-import-specifiers.cjs
- tsconfig.json
esbuild has [difficulty](https://github.com/evanw/esbuild/issues/708) with cases like "bundle these entry points, but don't bundle these specific files, treat them as separate imports, and don't bundle them into any other files that import them". This makes it hard to load `rh-gllobal-footer.js` separately.
Closes #429 
See https://github.com/RedHat-UX/red-hat-design-system/discussions/420#discussioncomment-3174377 (nice)
cc @eyevana
1. This commit replaces the per-element esbuild builds with a typescript build that uses a
[typescript transform](https://npm.im/ttypescript) to replace import specifiers ending with `css` with `css.js`, 
2. uses the node filesystem api to directly build shadow DOM css into their own javascript modules.
```
npm run build
```
check that the build is sane, try …
> chore: build with typescript

- .changeset/nervous-walls-love.md
- package.json
1. Added lib directory to `package.json` files block
I was unsure if I needed to run `npm i --package-lock-only` to update the package-lock.json.  I don't believe the files block is referenced there.
> chore: add lib directory to npm package

- .changeset/sharp-frogs-sing.md
- elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
- elements/rh-secondary-nav/rh-secondary-nav-menu-section.css
- elements/rh-secondary-nav/rh-secondary-nav.css
1.  Fixed missing font-family stacks when base css isn't applied
2.  Added rh-token CSS custom properties for font family stacks
3.  Fixed regression in spacing for slotted cta
> fix(secondary-nav): css style fixes

- .changeset/kind-suits-speak.md
- elements/rh-footer/rh-footer-lightdom.css
- elements/rh-footer/rh-footer.css
1. Fixes #462
2. Added logo styles to lightdom to minimize layout shift.
1. Visit https://deploy-preview-463--red-hat-design-system.netlify.app/components/footer/demo/
2. Replace the Red Hat logo with a partner logo by pasting the following code in the your browser console.
```
document.querySelector("rh-footer [slot=logo] img").setAttribute('src', 'https://catalog.redhat.com/img/svg/logo.svg')
```
3. Verify that the logo is 36px tall
> fix: added max-height to logo

- .changeset/smooth-rats-care.md
- elements/rh-secondary-nav/README.md
- elements/rh-secondary-nav/demo/dark-variant.html
- elements/rh-secondary-nav/demo/proxy.html
- elements/rh-secondary-nav/rh-secondary-nav-dropdown.ts
- elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
- elements/rh-secondary-nav/rh-secondary-nav.css
- elements/rh-secondary-nav/rh-secondary-nav.ts
- elements/rh-secondary-nav/test/fixtures.ts
- elements/rh-secondary-nav/test/rh-secondary-nav.spec.ts
1.  BREAKING: added color context provider decorators in place of variant attribute styling.
2. Replaced `#textDirection` method with `DirController` implementation for rtl support
3. Updated documentation to reflect changes
4. Added spec test for color-palette attribute
1. Locally test
1.  View changes on dark variant demo page.   This page will not yet work on ux. deploy previews
> refactor(secondary-nav)!: add color context and dir controller

- .changeset/tough-apes-doubt.md
- elements/rh-blockquote/rh-blockquote.css
1. Replaced hardcoded values with design tokens.
1. Check that Blockquote still renders as expected.
We have a few one off values currently in Blockquote that aren't in our tokens. 
- Author is body text with a weight of 500
- The left highlight border is 8px
- The left highlight border color is #43ADAF
> Add design tokens to rh-blockquote

- elements/rh-footer/RhFooter.ts
- elements/rh-footer/demo/proxy.html
- elements/rh-footer/rh-footer.css
1.  Added CSS parts for accordion-header and accordion-panel
2. Added RHDC specific `em` based overrides to the proxy demo
3. Cleaned up some of the previously incorrect grid gap settings around primary links
Some of the margins in the rh-global-footer are visibly incorrect.  These are being fixed in #476.
1. Visit `http://localhost:8000/components/footer/demo/`
2. Verify that, on desktop, the primary links have a 
- column gap of 32px
- row gap of 16px
Desktop primary links gaps
RHDC Desktop
RHDC Mobile
> fix (footer): add em based tokens example

- docs/components/footer.njk
1. Changed link for the Footer demo from https://github.com/RedHat-UX/rh-footer-demo to https://ux.redhat.com/components/footer/demo/.
1.
The [rh-footer-demo repo](https://github.com/RedHat-UX/rh-footer-demo) is going to be used for other component demos too, so it needed to be updated.
> docs: change demo link on the footer page

- elements/rh-secondary-nav/rh-secondary-nav-overlay.css
- elements/rh-secondary-nav/rh-secondary-nav.css
1. Fixes mobile menu to correctly overlay the page content
2. Fixes page scrolling when overlay is open
3. Closes #529
1. Open project on `fix/secondary-nav-scroll`
2. Load dev server `npm start`
3. Open demo for secondary-nav in browser mobile view.
> fix(secondary-nav): mobile menu and overlay scroll

- elements/rh-secondary-nav/rh-secondary-nav.css
1. Fixes nav height when a long logo title creates 3 lines
2. Closes #531 
1. Check out project on `fix/secondary-nav-long-logo-titles-height`
1. Load dev server `npm start`
1. Open demo for secondary-nav in browser mobile view.
> fix(secondary-nav): long logo title nav height

- elements/rh-secondary-nav/demo/dark-variant.html
- elements/rh-secondary-nav/demo/demo.css
- elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
- elements/rh-secondary-nav/rh-secondary-nav-overlay.css
1. Added padding of `10px` to the logo slot in lightdom.css
2. Corrected the dark variant demo to include adjusted logo type max-width for wider screens.
3. Removed "extra link" on the dark variant demo, long logo text has a direct effect on how many links you can include.
4. Reverts a previous change to `rh-secondary-nav-overlay` position styles made in misunderstanding of dev demo styles.
5. Closes #544 
1.  View [dark variant demo](https://deploy-preview-545--red-hat-design-system.netlify.app/components/secondary-nav/demo/dark-variant/)
2. View [default demo](https://deploy-preview-545--red-hat-design-system.netlify.app/components/secondary-nav/demo/)
Determine if 10px is appropriate padding around the logo text.   Please review in mobile view and desktop viewport sizes.  Look at both …
> fix(secondary-nav): logo text padding

- .changeset/slimy-eyes-rescue.md
- elements/rh-secondary-nav/demo/analytics.html
- elements/rh-secondary-nav/demo/demo.css
- elements/rh-secondary-nav/demo/rh-secondary-nav.html
- elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
- elements/rh-secondary-nav/rh-secondary-nav.ts
1. Wrapped the `<slot name="cta"><slot>` with `<rh-context-provider>` and apply correct `color-palette` attribute when in mobile view.
2. Closes #546
1. Go to the Secondary Nav Deploy Preview for the [Dark variant](https://deploy-preview-547--red-hat-design-system.netlify.app/components/secondary-nav/demo/dark-variant/) and the [Default](https://deploy-preview-547--red-hat-design-system.netlify.app/components/secondary-nav/demo/)
3. Set the viewport < 992px for the mobile compact nav view.
4. Open the mobile menu
Look for any possible combination of the mobile menu open/closed and at changing to different screen sizes to see if the color context can get out of sync.
> fix(secondary-nav): nav level cta color context on dark

- .changeset/brave-bobcats-attack.md
- elements/rh-secondary-nav/rh-secondary-nav-lightdom.css
- elements/rh-secondary-nav/rh-secondary-nav-menu.css
- elements/rh-secondary-nav/rh-secondary-nav-menu.ts
- elements/rh-secondary-nav/rh-secondary-nav.css
- elements/rh-secondary-nav/rh-secondary-nav.ts
1.  Moved overflow mobile menu list to an outer container.
2. Removed orphaned code.
3. Closes #559 
4. Closes #557
1. Go to the Secondary Nav Deploy Preview for the [Dark variant](https://deploy-preview-561--red-hat-design-system.netlify.app/components/secondary-nav/demo/dark-variant/) and the [Default](https://deploy-preview-561--red-hat-design-system.netlify.app/components/secondary-nav/demo/)
2. Set the viewport with height < 850px such as an iPhone.
5. Open the mobile menu.
6. Click "Other examples".
7. Try and scroll to CTA.  It should be visible
You should be able to scroll to and view the CTA when the mobile menu is open when viewing on netlify deploy preview.
However, if you run the code locally in the dev demo `npm start` you will have to remove the demo's overflows in order to …
> fix(secondary-nav): mobile menu overflow

- docs/get-started/fts-starter-kit.njk
1. Fixed broken link to Patternkit on FTS starter kit page
1. Visit Netlify demo and check "Browse Patternkit patterns" link on the FTS starter kit page.
> docs: fix Patternkit link on FTS starter kit page

- docs/get-started/fts-starter-kit.njk
1. Changed URLs on the FTS starter kit page that were internal only using a URL shortener
1. Go to `/get-started/fts-starter-kit/` and hover over the `Learn how to use FTS` and `Browse Patternkit patterns` links, they should start with `red.ht/...`
> Changed two URLs on FTS starter kit page

- elements/rh-alert/README.md
After our discovery today went in and added some README docs for the dismissable attribute and the close event it fires.
> docs(alert): adding dismissable and close event to readme

- .eleventy.cjs
- docs/_data/importMap.cjs
- package-lock.json
- package.json
1. Got fed up with having to constantly update the docs demos import map
2. found out about `traceInstall`
3. scratch my head at why scopes aren't applying correctly to the importmap
4. give up and cludge it as usual, just this time a little nicer
1. check the docs pages and demo pages in the DP
https://deploy-preview-626--red-hat-design-system.netlify.app/components/alert/demo/
https://deploy-preview-626--red-hat-design-system.netlify.app/components/blockquote/demo/
https://deploy-preview-626--red-hat-design-system.netlify.app/components/call-to-action/demo/
https://deploy-preview-626--red-hat-design-system.netlify.app/components/dialog/demo/
https://deploy-preview-626--red-hat-design-system.netlify.app/components/footer/demo/
https://deploy-preview-626--red-hat-design-system.netlify.app/ …
> docs: automatically generate import map with subpaths

- docs/_data/importMap.cjs
1. Added popperjs core back into the importmap as a static file until popperjs core can be removed. 
1. Go to the tooltip demo in the deploy link and the demo should look correct and have correct stylings now. 
#628
> fix(tooltip): demo broken - adding popperjs core back into the importmap file

- docs/get-started/design-system-kit.njk
- docs/get-started/fts-starter-kit.njk
- docs/scss/_utility.scss
1. Changed links going to `../../overview` to `../../get-started`
2. Fixed modal trigger in the "3. Load the library" box and used `rh-dialog` instead of `pfe-modal`
3. Removed `target="_blank"` from links
1. View deploy previews for the [Design system kit](https://deploy-preview-632--red-hat-design-system.netlify.app/get-started/design-system-kit/) page and the [FTS starter kit](https://deploy-preview-632--red-hat-design-system.netlify.app/get-started/fts-starter-kit/) page
> docs: fix links on Design system kit and FTS starter kit pages

- docs/foundations/typography.njk
1. Replaced broken `Typography availability` section on Typography page.
1. Go [here](https://deploy-preview-650--red-hat-design-system.netlify.app/foundations/typography/) and review the content.
> docs(typography): Fixed broken Typography availability section on Typography page

- .changeset/tender-lies-play.md
- package.json
In RH Product Trials we ran into an issue building where the `ScreenSizeController` exported from `@rhds/elements` gets exported as `@rhds/elements/elements/lib` due to the current export mapping.  This adds a `./lib/*` to the exports so we can bring in the ScreenSizeController and other libraries as we need from `@rhds/elements`
#654
> fix: 654 - Adding lib folder to exports in package json

- .changeset/honest-hornets-tap.md
- elements/rh-spinner/rh-spinner.css
- elements/rh-spinner/rh-spinner.ts
1. remove public `on` attribute from rh-spinner
1. put spinner on different contexts
2. make sure it looks good
3. make sure it doesn't have an `on` attr
4. toggle `on` attr with different values and make sure setting `on` attribute has no effect.
> fix(spinner): remove `on` attribute

- .changeset/long-colts-prove.md
- elements/rh-alert/rh-alert.css
- elements/rh-alert/rh-alert.ts
1.  Added a slot check for the Shadow DOM styles so the footer only gets the `margin-top` style when actions have been slotted in from the host. 
#656 
1. Go to the demo
3. Remove the actions from one of the alert elements
4. Inspect the Shadow DOM of that element, you should not see a `margin-top` on an empty footer now
5. You should still see the `margin-top` on the footers with actions slotted in.
> fix(alert): Adding logic to check for empty actions for margin-top

- .husky/pre-commit
- docs/about/how-we-build.njk
- scripts/scan-links.sh
1. add a short bash script to git's pre-commit hook
the script scans the docs and elements dirs on each commit and scans staged files for internal links. Pavlos Psomiadis provided the regexp's
1. add an internal link to a file (see `docs: fix internal link`) commit 
2. try to commit it, it should fail
> chore: scan files for links in precommit

- .github/ISSUE_TEMPLATE/1-new-component.yml
- .github/ISSUE_TEMPLATE/2-dev-handoff.yml
- README.md
1. Removed @methomps as the default assignee to new component requests and design to dev handoff requests and added @paigenotfound404.
This is just a chore, no changelog necessary.
> chore: changed assignee for github issue templates

- elements/rh-secondary-nav/demo/analytics.html
- elements/rh-secondary-nav/demo/dark-variant.html
- elements/rh-secondary-nav/demo/proxy.html
- elements/rh-secondary-nav/demo/rh-secondary-nav.html
- elements/rh-secondary-nav/demo/translation.html
1. Update `<pfe-icon>` usage in demos to use `set`.
1. check out  [deploy preivew ](https://deploy-preview-696--red-hat-design-system.netlify.app/components/secondary-nav/demo/)- icons should load in dropdown menus
> docs(secondary-nav): update pfe-icons in demos

- .changeset/two-wolves-push.md
- elements/rh-accordion/demo/right-to-left.html
- elements/rh-accordion/rh-accordion-header.css
- elements/rh-accordion/rh-accordion-header.ts
- elements/rh-accordion/rh-accordion-panel.css
- elements/rh-accordion/rh-accordion.css
- elements/rh-accordion/rh-accordion.ts
1.  Added logical properties to .toggle:after for the red border on the accordion elements
2. Added --_isRTL to handle whether or not the rotation of the icon needs to happen clockwise (applicable for right-to-left text) or counter-clockwise (applicable for left-to-right text)
> fix(accordion): adding right-to-left (rtl) styles

- .changeset/six-needles-study.md
- elements/rh-tooltip/rh-tooltip.ts
Noticed that the dark mode theme was not showing up for rh-tooltip after #693, fixing this issue. 
1.  Changed the color context to not default to `light` for rh-tooltip
2. Added the empty string backup for the on property.
1. [Go to the deploy preview demo for rh-tooltip ](https://deploy-preview-713--red-hat-design-system.netlify.app/components/tooltip/demo/)
2. Verify the dark mode theme looks correct
> fix(tooltip): dark context

- .changeset/fair-schools-deliver.md
- elements/rh-footer/rh-global-footer.ts
- elements/rh-footer/test/rh-footer.spec.ts
1. The fedora logo in `rh-global-footer` should always point to the Red Hat homepage no matter what site it's on.  I updated the logo url in the shadowroot to no longer be relative but absolute instead.
2. Added a test to check the logo slot for the absolute link to RHDC.
1. Go to https://deploy-preview-730--red-hat-design-system.netlify.app/components/footer/demo/
2. Click on the gray Fedora in the universal footer (rh-global-footer)
3. Verify that you were redirected to the Red Hat .com homepage (https://redhat.com)
> fix(global-footer): correct logo href

- .changeset/eight-garlics-grow.md
- package.json
1. remove husky step from postinstall when it's just users doing `npm i @rhds/elements`
> fix: remove husky from postinstall for users

- .changeset/spotty-moose-draw.md
- .changeset/spotty-moose-sculpt.md
- elements/rh-accordion/rh-accordion-header.css
- elements/rh-accordion/rh-accordion-header.ts
- elements/rh-accordion/rh-accordion-panel.css
- elements/rh-accordion/rh-accordion-panel.ts
- elements/rh-footer/rh-footer.css
1.  Added a shadow part on the rh-accordion-header container so we can override private CSS props
2. Added overrides to rh-accordion-header private CSS props to fix visual regressions switching from pfe-accordion to rh-accordion.
3. Removed a duplicate `id="container"` which was causing double border
1. Go to https://deploy-preview-742--red-hat-design-system.netlify.app/components/footer/demo/
2. Shrink the screen size until the footer accordion is visible.
4. Ensure that there are no unwanted regressions to the UI of the accordion.
There are two intentional regressions
1. The dropdown animation is now matching rh-accordion dropdown functionality
2. The size of the accordion headers coming from the rh-accordion spec
> fix(footer): accordion styles at mobile screen sizes

- .changeset/rude-carpets-switch.md
- elements/rh-alert/rh-alert.css
#655 
CSS update to the `rh-alert` element to replace the `1.5rem` value token that was used for the height / width and replace it with `var(--rh-size-icon-02, 24px)`.
> fix(alert): remove `rem` values from icon height, width

- .github/workflows/gzip.yml
1. add an action to report filesize in PRs
1. :shrug: make a pr, i guess. no need to tests IMO
> chore: add gzip-size action

- elements/rh-audio-player/rh-audio-player.css
- elements/rh-audio-player/rh-audio-player.ts
- elements/rh-menu/rh-menu.css
- elements/rh-menu/rh-menu.ts
1. remove all the dropdown/button/floating-ui stuff from menu 
2. reimplemented that stuff in audio-player
3. this fixes cross-root aria problems between the button and the menu, but does not provide for `activedescendent`
1. a11y audits and manual testing in blink, ff, and webkit
the floating-ui parts of this change need to be fiddled with, they're not ready to ship yet
> fix(menu)!: remove dropdown functionality

- .changeset/giant-cobras-tease.md
- elements/rh-subnav/demo/color-context.html
- elements/rh-subnav/demo/rh-subnav.html
- elements/rh-subnav/rh-subnav-lightdom.css
1. Added `rh-subnav-lightdom.css` to reduce layout shift before the element is defined
Closes #777 
1. View the [deploy preview demo](https://deploy-preview-781--red-hat-design-system.netlify.app/components/subnav/demo/) on a slow 3G network. 
Simulate a slow 3G network in the networks tab of the browser inspector.  Should be little to no layout shift as the page loads.
> fix(subnav): lightdom styles

- .changeset/rh-footer-copyright-row.md
- elements/rh-footer/rh-footer-lightdom.css
- elements/rh-footer/rh-footer.css
Closes #562 
1. span the copyright statement across all grid columns
https://deploy-preview-805--red-hat-design-system.netlify.app/elements/footer/demo/ at responsive widths, copyright should span the full width
> fix(footer): copyright spans whole row

- .changeset/silver-jars-wait.md
- elements/rh-accordion/rh-accordion-header.css
1. Removing overflow on `span` element from `rh-accordion-header` as it's causing visual error on mobile screens for `rh-footer`.
> fix(accordion): remove overflow from headers

- .changeset/remove-context-tokens.md
- elements/rh-accordion/rh-accordion-panel.css
- elements/rh-avatar/rh-avatar.css
- elements/rh-badge/rh-badge.css
- elements/rh-button/rh-button.css
- elements/rh-context-provider/rh-context-provider.css
- elements/rh-cta/rh-cta.css
- elements/rh-footer/docs/20-guidelines.md
- elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css
- elements/rh-subnav/rh-subnav-lightdom.css
- elements/rh-subnav/rh-subnav.css
- elements/rh-tabs/rh-tab.css
- elements/rh-tabs/rh-tabs.css
- lib/context/color/context-color.css
Depends on https://github.com/RedHat-UX/red-hat-design-tokens/pull/82
Closes #810 
1. remove all references to `--rh-context-*` tokens
2. replace the `--rh-context-text` and `--rh-context-background` tokens with "private" `--_context-*` vars
DPs:
The idea behind the context tokens is useful, but they were hastily implemented by yours truly without consulting the designers. Most of them were simple aliases to semantic tokens, and so have been replaced with such here in this PR. The exception to that rule are the `text` and `background` colours which were replaced with "private" css vars here in RHDS, which gives us some flexibility to determine our APIs before shipping.
> refactor: remove context tokens

- .changeset/tall-knives-kick.md
- elements/rh-cta/rh-cta.css
1. Made inner border for primary, secondary, and brick variants visible on hover and focus
1. View [deploy preview](https://deploy-preview-839--red-hat-design-system.netlify.app/components/call-to-action/demo/) and tab through or click CTAs to check that it shows the inner border
Closes issue #838
> fix(cta): make inner border visible in focus and active states

- .changeset/rh-alert-slotted-styles.md
- elements/rh-alert/rh-alert.css
1. sprinkle `!important` on to slotted styles
Closes #842
> fix(alert): prevent page styles from overriding component styles

- elements/rh-footer/test/rh-footer.spec.ts
1. Added time for the linked lightDOM CSS to load so that color contrast tests could pass.
2. Removed `it.skip('universal is accessible', function() { return expect(universalFooter).to.be.accessible(); });` on kitchen sink test because universal is part of the kitchen sink fixture represented by `element`. (`universalFooter` variable is not a fixture for this test.)
> fix(footer): a11y test failures

- .changeset/tame-ducks-raise.md
- elements/rh-tabs/demo/rh-tabs.html
- elements/rh-tabs/demo/rh-tabs.js
- elements/rh-tabs/rh-tab.css
- elements/rh-tabs/rh-tabs.css
1. `rh-tab.css`: provided a fallback when the context background color is not available.
2. `rh-tabs.css`: set background and text color to context values when present.
3.  Remove the context provider examples from the default demo, they are available in the color-context demo if needed.
Closes #865
1. View the [deploy preview for tabs](https://deploy-preview-866--red-hat-design-system.netlify.app/components/tabs/demo/)
2. On the default demo add `color-palette="darker"` to any tabs, it should gain the appropriate border colors, text color and background color.
3. View the [color-context demo for tabs](https://deploy-preview-866--red-hat-design-system.netlify.app/components/tabs/demo/color-context/)
4. All color-context settings should provide the correct background, text, and border …
> fix(tabs): default context colors 

- .changeset/color-palette-light.md
- .changeset/fair-chefs-tap.md
- .changeset/rh-navigation-secondary-default-palette.md
- elements/rh-navigation-secondary/README.md
- elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts
- elements/rh-navigation-secondary/rh-navigation-secondary.ts
- elements/rh-navigation-secondary/test/rh-navigation-secondary.spec.ts
- lib/context/color/provider.ts
1. Correct `colorPalette` property to use `light` default value to match design spec and token values
2. Added `light` to the `ColorPalette` type in the context provider
Closes #863 
1. View [Deploy preview demo for navigation-secondary](https://deploy-preview-864--red-hat-design-system.netlify.app/elements/navigation-secondary/demo/)
2. Nav bar should be #f0f0f0 on the default demo `color-palette="light"` (default)  
3. Should fix regression issue #863
> fix(navigation-secondary): correct colorPalette property

- docs/_includes/component/header.njk
1.  Added a `reverse` function to the `elementDocs` collection to fix the sorting issue in the side panel
1.  Check out the Deploy Preview and verify the elements are showing in the correct order
> Docs: fixing elementDocs "elements" sorting in the side panel

- elements/rh-accordion/rh-accordion-header.css
- elements/rh-accordion/rh-accordion-panel.css
Changed semantic token for the red border when accordions are expanded in rh-accordion-panel.css and rh-accordion-header.css. They previously used tokens from the brand red group or a danger border token.
Check that the border for the expanded accordion panel and header use either `var(--rh-color-accent-brand-on-light, #ee0000)` or `var(--rh-color-accent-brand-on-dark, #ff442b)` in the deploy preview.
Closes #876
> fix: change semantic token for the border when accordions are expanded

- .changeset/eleven-hounds-cry.md
- elements/rh-navigation-secondary/rh-navigation-secondary.ts
- elements/rh-navigation-secondary/test/rh-navigation-secondary.spec.ts
1. Realigned `color-palette` default to new surface token values
1. View [Deploy Preview,](https://deploy-preview-878--red-hat-design-system.netlify.app/elements/navigation-secondary/demo/) navigation-secondary background should match `--rh-color-surface-lighter` value of #f2f2f2
> fix(navigation-secondary): realign color-palette with surface tokens

- .changeset/ten-radios-decide.md
- elements/rh-alert/rh-alert.css
1. Updated the CSS for the slotted elements in the header container from `  --rh-font-family-heading: var(--_font-family) !important;` to `font-family: var(--_font-family) !important;`
1. [Go to the CTA demo](https://deploy-preview-892--red-hat-design-system.netlify.app/elements/call-to-action/)
2. Scroll down the page and confirm that the alerts on the page contain the font `RedHatText, "Red Hat Text", "Noto Sans Arabic", "Noto Sans Hebrew", "Noto Sans JP", "Noto Sans KR", "Noto Sans Malayalam", "Noto Sans SC", "Noto Sans TC", "Noto Sans Thai", Helvetica, Arial, sans-serif);`
> fix(alert): header slot will now use Red Hat Text font 

- docs/index.njk
- docs/scss/_base/_base.scss
- docs/scss/_utility.scss
- docs/scss/components/_example.scss
- docs/scss/components/_header.scss
I changed spacing between headings, body paragraphs, and other layout elements. Some of the spacing will still look funky until the proper `<section>` tags and heading levels are implemented or cleaned up on individual element and pattern pages.
In the deploy preview:
- The content on the Accordion and CTA pages have good examples to check spacing and heading styles.
- Check the homepage to make sure body copy is the right size.
- Check that the border radius for cards or example containers are 8px.
CLoses #919
> docs: fix spacing and typography 

- docs/_includes/component/header.njk
- docs/_plugins/rhds.cjs
- docs/elements/index.md
1. We're using the `elementDocs` collection when generating the side nav, but it's not created/sorted with the other collections used in the `RHDSAlphabetizeTagsPlugin`. Before returning, I'm sorting `elementDocs` by the slug since it takes a component's alias into consideration. 
1. Run the docs with `npm run start` locally and verify that the elements are listing in alphabetical order in the side navigation under `Elements`.
> docs: sort elementDocs alphabetically by slug

- docs/_includes/feedback.html
- docs/scss/styles.scss
1. Removed margin from feedback and foundations section wrapper.
Closes #944
> docs: remove margin from feedback section

- docs/scss/_utility.scss
- docs/scss/components/_example.scss
1. Moved example `img` references to `var(--inline-img-max-width, 100%)` from `width` to `max-width`.
2. Set example `img` references width to `auto`.
1. Check [DP](https://deploy-preview-980--red-hat-design-system.netlify.app) for issues with image size.
> docs(example): fixes example img CSS

- docs/_plugins/shortcodes/example.cjs
- docs/scss/components/_example.scss
- elements/rh-spinner/docs/20-guidelines.md
1. Modified example SCSS for docs for an example image with no palette, or "none" as described in #1023 .
2. Added "none" option in example shortcode documentation for palette.
1. Go to the [first image under Sizes heading on Spinner's Guidelines page](https://deploy-preview-1024--red-hat-design-system.netlify.app/elements/spinner/guidelines/#sizes) .
2. Image should have no padding.
3. Image should have no border.
3. Image should have no background.
4. Image should should be responsive.
Style should be similar [what it currently looks like on ux.redhat.com](https://ux.redhat.com/elements/spinner/guidelines/#sizes) but possibly less blurry.
> docs(example-image-no-border): added styles for example image

- elements/rh-alert/demo/alternate.html
- elements/rh-alert/demo/dismissable.html
- elements/rh-alert/demo/states.html
- elements/rh-alert/demo/toast.html
#1047
1.  Updated the provider paths for `rh-alert`
Go to the following deploy previews and verify they are working: 
- [Alternate](https://deploy-preview-1048--red-hat-design-system.netlify.app/elements/alert/demo/alternate)
- [Dismissable](https://deploy-preview-1048--red-hat-design-system.netlify.app/elements/alert/demo/dismissable)
- [States](https://deploy-preview-1048--red-hat-design-system.netlify.app/elements/alert/demo/states)
- [Toast](https://deploy-preview-1048--red-hat-design-system.netlify.app/elements/alert/demo/toast)
> docs(alert): context provider path fix for demos

- elements/rh-footer/docs/30-code.md
1. Split out subcomponents on code tab into their own sections containing each section of shortcode, `slots`, `attributes`, `methods`, `events`, `cssparts`, and `csscusomtproperties`. 
Closes #948
1. View deploy preview
Now that some of these sub components APIs are exposed we should consider adding more detail to the JSDoc around css parts and slots on these components either as part of this PR or as a new issue.
> docs(footer): split out all subcomponents on code tab

- elements/rh-cta/docs/20-guidelines.md
1. add a class to a markdown list in order to make the markdown and njk parsers work nice together
1. dp browse to /elements/call-to-action/guidelines/#call-to-action-text-labels
2. 
```js
console.assert($('[src="/elements/call-to-action/cta-text-labels-411w.png"]').closest('ul') === null)
```
> docs(cta): pop example out of list

- elements/rh-audio-player/rh-audio-player.ts
1. Added resize observer to check for player layout changes and update menu position accordingly
1. 1Use the [default DP demo](https://deploy-preview-1101--red-hat-design-system.netlify.app/elements/audio-player/demo/).
2. Click the More options menu button (kebab icon) to open the menu.
3.  Adjust window width until the player layout changes.
4.  Verify that the menu position updates so that it stays with the player.
> fix(audio-player): added resize observe to reposition menu

- elements/rh-audio-player/rh-audio-player.ts
1. Removed unnecessary focus() on menu button when menu is closed
1. Go to the [Prevent concurrent playback demo from the DP](https://deploy-preview-1107--red-hat-design-system.netlify.app/elements/audio-player/demo/prevent-concurrent-playback/).
2. Click the **More options** menu button (kebab icon) on the _**first**_ player.
3. Click the **More options** menu button (kebab icon) on the _**second**_ player.
4. Verify that the **More options** tooltip appears only on the _**first**_ player.
5. For good measure, try clicking and using the keyboard to jump between various buttons on the players, opening and closing the menus.
6. Verify that the focus and tooltips behave as expected.
> fix(audio-player): tooltip duplication

- docs/_plugins/shortcodes/repoStatus.cjs
- docs/scss/components/_component-status-table.scss
- package-lock.json
- package.json
Closes #424
1. Using markdown for repo status table header so that it automatically adds the permalink/copy functionality
2. Removed some markup and the heading element ID that I don't see being used anywhere
1. Verify that the permalink/copy functionality appears and works on the `Repo status` heading.
2. Verify that you now see SVG checks now instead of the HTML entities
> docs: add permalink/copy to repo status table header & use SVG for check

- docs/_plugins/rhds.cjs
- eleventy.config.cjs
closes #962
... hopefully?
1. stop bundling rhds on each 11ty build
2. exclude `.js.map` from 11ty watch
> docs: don't bundle rhds before build

- docs/scss/_utility.scss
1. Changed container max-width CSS from 65rem to 1000px;
From a large desktop window, view the following pages from the DP and verify that `.container`, `.header` and `.section` are consistently a max-width 1000px: 
Max-width was initially 65em, but we (a call between @zeroedin and me) had to changed it to 65rem because it was inconsistent in some of the tokens pages.  I'm assuming this was what broke. Setting it to 1000px should keep it consistent across the site.
> docs: set container max-width to 1000px;

- .changeset/popular-crews-relate.md
- elements/rh-audio-player/rh-audio-player.ts
1. Fixed name of subscribe slot on audio-player
1. Go to https://deploy-preview-1168--red-hat-design-system.netlify.app/elements/audio-player/code/#slots
2. Verify that there is now a slot named 'subscribe'
> docs: correct subscribe slot

- docs/get-started/design-system-kit.njk
- docs/get-started/fts-starter-kit.njk
- docs/scss/_utility.scss
fixes #1159
1. replace bespoke patterns with cards
2. simplify selectors and scss
3. use tokens where possible
4. replace link-to-open-dialog with card action button
https://deploy-preview-1182--red-hat-design-system.netlify.app/get-started/fts-starter-kit/
https://deploy-preview-1182--red-hat-design-system.netlify.app/get-started/design-system-kit/
This isn't a pixel perfect refactor. first, we're fixing the broken layout, second, the dialog was not imported and thus broken, third, the colours and spaces were not tokens from the design system, and last, links should not be used to trigger a dialog (cc @nikkimk can you gut check me on that last one? there aren't any guidelines on triggering elements in the docs pages for dialog).
> docs: fix card grids

- docs/assets/tokens/tokens.css
1. Fix token icon `<samp>` size 
Closes #1199
1. View [deploy preview](https://deploy-preview-1202--red-hat-design-system.netlify.app/tokens/icon/)
> docs: fix tokens icon samp element size

- docs/_plugins/shortcodes/repoStatus.cjs
1. Returning an empty string instead of the repo status table until we find a better [solution](https://github.com/orgs/RedHat-UX/discussions/1173) for maintaining the data. 
1. Go to all the pattern and element overviews and verify that the repo status table is hidden.
I tried commenting them out in the MD files, but the comment was prematurely closed from the HTML comments in the shortcode code. 
Closes https://github.com/RedHat-UX/red-hat-design-system/issues/1174
> docs: don't render repo status table

- elements/rh-tag/docs/20-guidelines.md
1. Added the red border and danger icon for the Best Practices examples
1. Check the DP's [tag page](https://deploy-preview-1313--red-hat-design-system.netlify.app/elements/tag/guidelines/#best-practices)
- Is the formatting for the dark theme tags example ok?
> docs(tag): update formatting of best practices examples

- .changeset/tag-on-dark.md
- elements/rh-tag/rh-tag.css
1. fix tag css formatting and some bugs that resulted from lack of linting
2. ensure that tags on dark contexts are always white (per existing guidelines)
This doesn't fix #1294 , but it does address a bug in tag, whereby tags can be rendered illegible on dark surfaces. A follow-up PR should close #1294 by updating the guidelines and implementing dark colours for tag, but this PR should still land in caterpie in order to prevent contrast errors.
> fix(tag): legibility on dark contexts

- lib/elements/rh-context-picker/rh-context-picker.ts
- package.json
1. fix context picker so that it's change event stops at its target.
2. add `npm run serve` command to spin up 11ty dev serve only (without wds)
1. check this out on the context branch in the cards demo on that page. changing the nested context shouldnt' change the parent context.
> fix(lib): picker scope

- .changeset/card-footer-layout.md
- elements/rh-card/demo/grid.html
- elements/rh-card/demo/rh-card.html
- elements/rh-card/rh-card.css
1. make the card's footer area always align to the bottom of the card 
2. add a demo which links to the relevant guidelines
1. check in various conditions (with proxy)
> fix(card): vertical alignment of footer

- .changeset/wet-flowers-double.md
- elements/rh-navigation-secondary/rh-navigation-secondary-dropdown.ts
1. Fixed initialization of current page indicator.  Should load initial state after setting up the mutation observer.
Closes #1334
1.
> fix(navigation-secondary): initialization state of current page indicator

- .changeset/blockquote-margin.md
- elements/rh-blockquote/rh-blockquote.css
Fixes #1332
1. remove the margin from blockquote
> fix(blockquote): remove margin

- docs/_plugins/shortcodes/renderInstallation.cjs
- docs/assets/elements/uxdot-installation-tabs.js
Fixes #1361
1. fix my careless error from fc27b791
1. check the [DP](https://deploy-preview-1366--red-hat-design-system.netlify.app/elements/audio-player/code/), see if the tabs (a) work and (b) look right
> docs: code installation tabs

- .changeset/itchy-dogs-matter.md
- elements/rh-tabs/rh-tab-panel.ts
1. removed `color-palette` attribute
1.
`color-palette` in the case of panels was never wired up.  Using it would not provide any change to the component.  My assumption is is a minor but maybe we can get away with a patch change?  Discussion on this is in the issue [#1353 ](https://github.com/RedHat-UX/red-hat-design-system/issues/1353) In the future we'd suggest using `<rh-surface>` inside of the panel.
> fix(tabs): remove color provider from `rh-tab-panel`

- docs/index.njk
1. To fix #1201 , I replaced the redundant "Submit feedback" link text in the main Contribute section of the homepage with "Join the discussion." There is already another interactive element with "Submit feedback" text in the navigation section of the site.
2. Changed the link destination, so that instead of pointing to our Get Started page, it points directly to the GitHub discussions page. This basically saves users a step, since that Get started page's feedback section is already little more than a link to the discussions page.
1. Go to the [Contribute section](https://deploy-preview-1375--red-hat-design-system.netlify.app/#contribute) of the deploy preview RHDS homepage (just before the footer).
2. In this section, confirm that the text of its sole link now reads "Join the discussion" …
> docs: clean up feedback/discussion link

- .changeset/card-first-p.md
- elements/rh-card/rh-card.css
1. fix various issues with rh-card (see changeset)
2. cherry-picked those fixes from the #1350 for ease of review
> fix(card): layout for first slotted p

- elements/rh-table/rh-table-lightdom.css
1. The previous token was `--rh-color-blue-50-rgb`, which now shows as a darker blue in Tokens 2.0. I changed it to `--rh-color-blue-10-rgb`. Looks like the stylelint didn't change it because it was an existing token name.
Verify that the sample table in the UX dot DP and the `<rh-table>` demo look like the `After` image.
**Before:**
**After:**
> fix(table): change blue crayon token for the hover state's column background color

- elements/rh-footer/rh-footer.css
- elements/rh-pagination/rh-pagination-lightdom.css
- elements/rh-pagination/rh-pagination.css
- elements/rh-spinner/rh-spinner.css
- elements/rh-table/rh-table.css
- elements/rh-tabs/rh-tabs.css
I checked CSS of elements that use crayon color tokens to make sure that the stylelint migration rules updated them correctly. I found that the linter changed the fallback hex value for gray tokens, instead of the token names. Checked what the colors were in RHDS 1.2.0 to correct the token names and values.
1. Check gray tokens in the demos for footer, pagination, spinner, table, and tabs 
No need for all three of you to review. Just tagged you all to see who's able to do it first. :)
> fix: token migration errors

- elements/rh-tabs/docs/20-guidelines.md
Added a couple sentences to the "Guidelines" page's "Inset" section about how panel padding can be removed with custom code
Check the bottom of the [Inset section](https://deploy-preview-1404--red-hat-design-system.netlify.app/elements/tabs/guidelines/#inset).
Do you think there needs to be any additional documentation about inset/tab panel padding?
> feat: add content about tabs panel padding

- elements/rh-accordion/BaseAccordion.ts
- elements/rh-accordion/rh-accordion-header.ts
- elements/rh-accordion/rh-accordion.ts
Closes #1406 
- refactor accordion's render method
- while we're at it, remove `BaseAccordion`
https://deploy-preview-1407--red-hat-design-system.netlify.app/elements/accordion/demo/color-context/
> fix(accordion): revert regression in header context

- docs/_includes/component/header.njk
Closes #1444 
1.  Fixed the header template to only show active when it's on the top level of the about section
1.  Should not double highlight rows on the side-nav in the about section anymore
> docs: fixing side nav in about section

- docs/get-started/designers.md
1. Added descriptions for tier 1 events, brand media, and page builder libraries
1. Check page in [DP](https://deploy-preview-1463--red-hat-design-system.netlify.app/get-started/designers)
> docs: add subsystems to Designers page

- .changeset/angry-lemons-shop.md
- elements/rh-tabs/rh-tabs.ts
1. Fixed call to static issues, should be targeting a class static method not instance static method.  This bug stops the component from correctly resizing to mobile horizontal scrolling.
Closes #1466 
1. View [Tabs demo](https://deploy-preview-1467--red-hat-design-system.netlify.app/elements/tabs/demo/)
To test this you need to first remove the `display: grid` from the `main` element in the demo via the inspector 👎
> fix(tabs): static instances

- .changeset/late-shrimps-shake.md
- docs/elements/elements.html
- elements/rh-tile/rh-tile-lightdom.css
1. Updated the lightDOM CSS for tile so that headline links have the highest z-index.
1. Go to [DP Tile docs](https://deploy-preview-1471--red-hat-design-system.netlify.app/elements/tile/).
2. Ensure that every tile example has a headline link click target that covers the entire card.
> bug(tile): z-index issue with headline link

- docs/about/how-we-build.njk
- docs/design-code-status.njk
- docs/index.njk
Fixed broken PatternFly and PFE links on UX dot.
Check links in the DP's:
- [Homepage](https://deploy-preview-1478--red-hat-design-system.netlify.app/)
- [How we build page](https://deploy-preview-1478--red-hat-design-system.netlify.app/about/how-we-build/)
- [Design/code status page](https://deploy-preview-1478--red-hat-design-system.netlify.app/design-code-status/)
Some of these links open in a new tab. I didn't fix that in this PR and can open a new issue instead.
> docs: fix PF and PFE links

- package.json
1. Add `analyze` command to npm scripts, caused `npm run new` to fail.  See #1482 
1.  Create a new component with `npm run new`
> fix: add analyze to npm scripts

- elements/rh-audio-player/docs/40-code.md
- elements/rh-button/docs/30-code.md
- elements/rh-tile/docs/30-code.md
- elements/rh-tooltip/docs/30-code.md
For the docs **Code** page of each of the following elements, I fixed the link to the **View the demo in a new tab** link:
- `rh-audio-player`
- `rh-button`
- `rh-tile`
- `rh-tooltip`
In the DP, go to each of the following pages, and make sure the **View the demo in a new tab** link is correct:
- [Audio player](https://deploy-preview-1493--red-hat-design-system.netlify.app/elements/audio-player/code/#usage)
- [Button](https://deploy-preview-1493--red-hat-design-system.netlify.app/elements/button/code/#usage)
- [Tile](https://deploy-preview-1493--red-hat-design-system.netlify.app/elements/tile/code/#usage)
- [Tooltip](https://deploy-preview-1493--red-hat-design-system.netlify.app/elements/tooltip/code/#usage)
> docs: updated usage demos url on element code tags

- .changeset/spicy-cups-fly.md
- .gitignore
- eslint.config.js
- package.json
- scripts/generate-react-wrappers.ts
1. :vomiting_face: added react wrappers :wastebasket: 
1. steal someone else's computer
2. install react
3. actually don't, but try importing this from esm.sh into codepen after publishing and then open an issue if it's busted :sparkles:
> feat: react wrappers

- .changeset/large-kings-drop.md
- elements/rh-button/rh-button.ts
- elements/rh-menu/demo/color-context.html
- elements/rh-menu/demo/position-left.html
- elements/rh-menu/demo/position-right.html
- elements/rh-menu/demo/position-top.html
- elements/rh-menu/demo/rh-menu.html
- elements/rh-menu/rh-menu.css
- elements/rh-menu/rh-menu.ts
1.  `<rh-menu>`: 
- Added  `delegatesFocus:true` and `focus()` to improve the keyboard navigation accessibility on firefox
- Improved demos by removing uneeded trigger button `slot="button` elements.
- Fixed CSS bug where padding was only applied to dark slotted a tags
2. `<rh-button>`: Added  `focus()` to ensure the shadow button receives focus from firefox.
1.  View  Menu [Deploy preview demo](https://deploy-preview-1529--red-hat-design-system.netlify.app/elements/menu/demo/)
2. View Audio Player integration [Deploy preview demo](https://deploy-preview-1529--red-hat-design-system.netlify.app/elements/audio-player/demo/)
Please review Audio player's implementation as well.
> fix(menu): improve keyboard accessibility on firefox

- package.json
1. Improved running speed of `npm run test` I believe we don't need the full build stack as a dependency for tests such as the docs and artifact builds.
2. Created `build:test` which reduces deps needed for test runs.
1.
> chore: improve test run speed by removing full build deps

- docs/_plugins/shortcodes/repoStatus.cjs
1. This MR fixes https://github.com/RedHat-UX/red-hat-design-system/issues/1550
2. Added a span around rh-tag (overall status) in the Repo Status table to fix the extra padding issue in mobile view
1. Go to https://ux.redhat.com/design-code-status/
3. Check the mobile view for the repo status table
4. the overall status i.e New, Experimental, Beta should not have extra padding in mobile view
> docs: fix repo-status tag padding in mobile

- docs/get-started/designers.md
- docs/get-started/developers/index.md
1. Add link to designer accessibility docs to "Get started: Designers"
2. Add link to developer accessibility docs to "Get started: Developers"
- Check links in DP: ["Get started: Designers"](https://deploy-preview-1553--red-hat-design-system.netlify.app/get-started/designers/#learn-about-our-design-system) (under "Accessibility") and ["Get started: Developers" ](https://deploy-preview-1553--red-hat-design-system.netlify.app/get-started/developers/#learn-about-our-design-system) (under "Documentation")
> docs(get started): add links to accessibility docs

- docs/_plugins/shortcodes/renderInstallation.cjs
- docs/assets/elements/uxdot-installation-tabs.js
- docs/elements/elements.html
1. Fix installation tabs by using `rh-tab-panel` instead of `uudot-installation-tab-panel`
2. Progressively enhanced styles on `rh-tab-panel` to ensure panel content fit.   
1.
> docs: progressively enhanced tab panel on installation tabs

- elements/rh-tabs/demo/nested.html
1. Add a nested demo
Closes #1481 
1.  View [nested demo](https://deploy-preview-1573--red-hat-design-system.netlify.app/elements/tabs/demo/nested/)
@eyevana here is a demo showing nested tabs working.  The bug outlined in #1481 was fixed by our implementation changes from a tabs-controller to aria-tabs-controller upstream in pfe.  https://github.com/patternfly/patternfly-elements/pull/2699
Thanks for filling the issue!
> chore(tabs): add a nested demo

- .changeset/curly-jobs-eat.md
- elements/rh-tabs/rh-tabs.css
- elements/rh-tabs/rh-tabs.ts
- elements/rh-tabs/test/rh-tabs.spec.ts
1. Added support for rtl overflow buttons, inverting scroll methods and icons
Closes #1304
1. View [tabs RTL demo](https://deploy-preview-1575--red-hat-design-system.netlify.app/elements/tabs/demo/right-to-left/) 
View at a screen size where tabs overflows and overflow buttons appear
> fix(tabs): invert scroll functions when rtl, flip icons

- web-dev-server.config.js
fixes dev server loading build js. removes need to restart server for css changes
1. redirect dev server to typescript sources
1. `npm run dev`, then change some element css
> chore: dev server load ts sources

- docs/accessibility/assistive-tech.md
- docs/accessibility/q-a-testing.md
- docs/accessibility/resources.md
1. Added a new page for assistive technologies
2. Added a few new resources to the a11y resources page.
1. View the preview [assistive tech page](https://deploy-preview-1638--red-hat-design-system.netlify.app/accessibility/assistive-tech/). (Entire page is new)
2. View the preview [resources page](https://deploy-preview-1638--red-hat-design-system.netlify.app/accessibility/resources/). (Added TetraLogical A11y Quick Tests to the general a11y testing section. Added Google A11ycasts, Web Accessibility Perspective Videos, and the US Dept of Ed OCR Video Series to the training section.)
3. Ensure the links to these pages appear in the Accessibility section of the site nav.
> docs: add assistive tech page and new resources

- docs/assets/javascript/elements/uxdot-sidenav.js
1. Added padding to the `<ul>` in Side Nav to allow for overflow scroll to the last item
1. Expand larger sections, like Tokens, and try to scroll down to "Get support"
2. Compare to live [ux.redhat.com](https://ux.redhat.com)
Closes #1660
> bug(docs): fix Side Nav overflow scroll

- .changeset/strong-snails-reflect.md
- elements/rh-navigation-secondary/rh-navigation-secondary.ts
- elements/rh-navigation-secondary/test/rh-navigation-secondary.spec.ts
1. applied navigation role to host using internals
2. removed shadow nav element
Closes #1655
1. View deploy preview, change `aria-label` on host to a different value, that value should update in accessibility tree, and removing it will change it back to "secondary"
> fix(navigation-secondary): improved accessibility customization

- docs/_plugins/shortcodes/repoStatus.cjs
1. Fixed whitespace in repostatus that causes markdown to convert it to `<p>` tags when they shouldn't exist.
1.
> docs: fix whitespace in repo status rh-tags

- docs/support/index.md
1. Updated `File a bug report`, `Request a feature or component`, and `Report a bug on ux.redhat.com` links to new issue templates
1. Go to [Support page](https://ux.redhat.com/support/)
2. Double check those 3 tile links work ok?
> docs(support-page): updating issue links

- docs/get-started/developers/index.md
1. Fixed broken links
1. Go to [Developers' Get Start page](https://ux.redhat.com/get-started/developers/)
2. Check the `foundations`, `elements`, and `patterns` links work (see image below)
Closes: #1672
> docs(dev-getstarted): fixing broken links

- docs/_includes/layouts/pages/elements.njk
1. hide the demos tab when the list is empty
1. check that demos tab exists for e.g. alert
2. ensure that it does not for e.g. popover
> docs: hide demos tab when there are none

- docs/elements/demos.html
1. Fixed the URL for each "View Fullscreen" link on the Demos page for each RHDS element.
1. [Visit the DP](https://deploy-preview-1688--red-hat-design-system.netlify.app/elements/card/demos/) and go to Elements > {{ Any Element }} > Demos. 
1. Scroll down and verify "View Fullscreen" works for each demo
* Both the "base" element demo, color context, and any other variants.
The URLs are broken for every "base" element on ux.redhat.com right now. 
For example, the URL for "View Fullscreen" for CTA's variants work; however, the "base" URL for "View Fullscreen" for CTA does not. This PR fixes that.
> docs: fix base "View Fullscreen" link URL on element Demos pages

- docs/foundations/typography.md
1. Added an `alt` attribute to the Red Hat Display/Text sample image.
1. Go to the [DP's Typography page](https://deploy-preview-1691--red-hat-design-system.netlify.app/foundations/typography/#style).
2. Inspect the image in the Style section.
3. Make sure the `<img>` element has a populated `alt` attribute.
> docs: Added alt text to Typography page image

- docs/design-code-status/index.md
1. Added an `aria-label` value to each of the five sample icons at the top: "{status} icon"
1. Go the [DP Design/code status page](https://deploy-preview-1697--red-hat-design-system.netlify.app/design-code-status/).
2. Inspect the sample tag icons in the Overview section's table.
3. Verify that each icon has a populated `aria-label` attribute.
There are other ways to test (e.g., via a11y plugins), so do as you see fit. But the above does the trick.
> docs: add aria-labels to sample icons on status page

- docs/patterns/card/index.md
1. Added an `alt` attribute to a picture of a cat.
1. Go to the [DP card pattern page](https://deploy-preview-1699--red-hat-design-system.netlify.app/patterns/card/#image-title-bar)
2. Inspect the picture of the kitten 
3. Verify that it has a populated `alt` attribute.
> docs: added alt text to kitten image on card pattern page

- .changeset/tiny-melons-help.md
- elements/rh-tile/demo/color-context.html
- elements/rh-tile/rh-tile.css
1. Fixed the headline, title, body text, and footer font-sizes to match the [Tile specs](https://www.figma.com/design/8cZsqpCsq3KyiHf5VyBuRO/Element---Tile?node-id=507-2284&m=dev) for both the default and compact variants.
1. Inspect the font-sizes of the headlines, title, body, and footer in the demos and ensure they match both variants in the spec.
2. Dev: check that my CSS looks good too, and that there should be no repercussions (e.g., with my `!important` flags).
Closes: #1591
> fix(tile): tile headline size

- netlify.toml
1. redirect `/components/get-started/` to `/get-started/`
see https://github.com/orgs/RedHat-UX/discussions/1704#discussioncomment-10011187
> docs: redirect from /components/get-started

- elements/rh-navigation/docs/00-overview.md
1. Fixed the broken link at the bottom of the Nav element Overview page
1. Checkout out the Nav element Overview page in the deploy preview
2. Compare with the [broken live version](https://ux.redhat.com/elements/navigation-primary/)
> docs(nav): fixing broken link on Nav element Overview

- .changeset/breezy-bears-judge.md
- elements/rh-card/rh-card.css
1. Added an `!important` to the `margin: unset` on headings slotted into `header` to prevent inheriting margins, like in the [card patterns](https://github.com/RedHat-UX/red-hat-design-system/pull/1188#issuecomment-2256012174) per @zeroedin's [proposed solution](https://github.com/RedHat-UX/red-hat-design-system/pull/1188#issuecomment-2256237360)
1. Check this fixes the [Title Card pattern](https://deploy-preview-1188--red-hat-design-system.netlify.app/patterns/card/examples/#title-bar-card)
2. Double check there are no unintended consequences across the demos
> fix(card): adding important to margin unset for headings

- CONTRIBUTING_DESIGN.md
- docs/_data/repoStatus.yaml
- docs/_includes/layouts/base.njk
- docs/_includes/layouts/pages/basic.njk
- docs/_includes/layouts/pages/elements.njk
- docs/_includes/layouts/pages/home.njk
- docs/_includes/layouts/pages/tokens.njk
- docs/_includes/partials/component/sidenav.njk
Added a quick and dirty icon fix so that in-progress elements are more easily distinguished. 
1. View the docs site, check to see if there is a caution icon next to the element navigation item AND next to the title within the element main page.
Full disclaimer, I realize that there's likely a much much much better way to do this 😅. However, seeing as it's a pretty sore pain point, this would band-aid the issue until a proper fix is in place.
Thanks for considering it!
Closes https://github.com/RedHat-UX/red-hat-design-system/issues/1733
> docs: quick and dirty icon update for in progress elements

- .changeset/loud-spies-work.md
- elements/rh-button/rh-button.css
- elements/rh-button/rh-button.ts
1. Centered the icon in the "play" variant of `<rh-button>`.
1. First, view the "play" variant of `<rh-button>` in production [on uxdot](https://ux.redhat.com/elements/button/demo/variants/).
* Note how it is not centered in the black circle
2. Now, go to the [variants demo](https://deploy-preview-1731--red-hat-design-system.netlify.app/elements/button/demo/variants/) in this DP.
3. Notice how the play icon is now centered in the circle.
If you look at the `<rh-button>` [Figma](https://www.figma.com/design/j7Rjo2W6PLloxOSXQOpll0/Red-Hat-Design-System-library?m=auto&node-id=451-3138), you'll notice the play button does _not_ have rounded corners. [The docs](https://ux.redhat.com/elements/button/) for `<rh-button>` also reflect this.
If you look at the [current …
> fix(button): center play icon in circle

- docs/_includes/layouts/demo.njk
Removed some styles affecting the layout of certain elements in full screen demos.
Visit any of the elements named below in [this PR's DP](https://deploy-preview-1774--red-hat-design-system.netlify.app/) and compare the demos to [the DP for `staging/charmander`](https://deploy-preview-1567--red-hat-design-system.netlify.app/).
For example, compare the rh-button full screen demo in the [staging/charmander DP](https://deploy-preview-1567--red-hat-design-system.netlify.app/elements/button/demo/) versus [this PR's DP](https://deploy-preview-1774--red-hat-design-system.netlify.app/elements/button/demo/).
Of note: while this PR doesn't depend on `staging/charmander`, it does pre-emptively fix an issue introduced there. 
Here's a list of elements where these styles messed with each element's …
> docs: remove fullscreen demo styles

- .changeset/silly-turtles-hang.md
- elements/rh-accordion/rh-accordion-header.ts
1. Removed deprecated icon property from header
Closees #1748 
1.
Unless I'm missing it, the icon property didn't appear to be used or its functionality had already been removed.  Please check me here.
> fix(accordion): remove deprecated icon property from header

- docs/accessibility/resources.md
1. Fixed Udacity course URL on accessibility resources
1. Double check the link works
> docs: fix Udacity course URL

- docs/assets/javascript/elements/uxdot-sidenav-lightdom.css
- docs/assets/javascript/elements/uxdot-sidenav.js
1. Removed the inherited underline from links in the sidenav
1. Check it looks right on the deploy preview
2. Check the code in the lightdom CSS is the right way to go
> docs: remove sidenav links underlines

- docs/release-notes/index.md
1. Fixed the link/href for `rh-table` lightdom CSS (there was a space messing up the path, causing it to 404)
1. Double check everything looks ok on the [Release Notes page](https://deploy-preview-1795--red-hat-design-system.netlify.app/release-notes/)
> docs: fixing rh-table lightdom CSS link/href path

- docs/_plugins/shortcodes/repoStatus.cjs
- docs/design-code-status/index.md
1. Fixed the `rh-tag` icon situation in the `repoStatus` tables since they were either not showing or the positioning and spacing was off.
For example:
1. Double check the [Design/code status page](https://deploy-preview-1796--red-hat-design-system.netlify.app/design-code-status/) and at least one element's Overview page to ensure the status tables look ok.
2. Double check code is quality
Should look something like this:
> docs: fixing repoStatus tag icons

- docs/release-notes/index.md
Relase Notes page on mobile before the changes:
After these changes:
1. Visit the [Release Notes page in the DP](http://localhost:8080/release-notes/)
2. Shrink your browser down to mobile viewports
3. Make sure it's readable
> docs: fix layout of release notes table on mobile

- eslint.config.js
1. Correct the path to the `uxdot-elements` in the eslint ignores.
1.
> chore: correct eslint path to uxdot-elements.js in ignores

- docs/_data/repoStatus.yaml
1.  Align components names to match the naming convention used in the subnav.
2.  Fixes missing rh-tag's in subnav when a component is still in planning.
1.
> docs: fix repoStatus naming convention

- .changeset/giant-planets-argue.md
- .changeset/gorgeous-impalas-knock.md
- .changeset/swift-nails-notice.md
- docs/_includes/partials/component/header.njk
- docs/assets/javascript/elements/uxdot-sidenav.ts
- elements/rh-accordion/rh-accordion.ts
- elements/rh-navigation-secondary/demo/analytics.html
- elements/rh-navigation-secondary/rh-navigation-secondary.ts
- elements/rh-subnav/demo/dynamic.html
- elements/rh-subnav/rh-subnav.ts
1. removed RTI from `rh-subnav`,`rh-navigation-secondary`, `uxdot-sidenav` as previously discussed with @hellogreg and @adamjohnson 
2. Corrects `rh-subnav` icons.
3. added `accessible-label` to `rh-subnav` and `rh-navigation-secondary`.  
1.
> fix: remove rti from navigations

- .changeset/wild-foxes-smoke.md
- elements/rh-navigation-secondary/rh-navigation-secondary-lightdom.css
1. Corrects logo-height for logo text to use the 130% value aka `var(--rh-line-height-heading, 1.3)`
Closes #1746 
1.
> fix(navigation-secondary): correct line height logo text

- .changeset/selfish-spies-fry.md
- elements/rh-button/rh-button.css
1.  Removed errant `:host { display: contents}`
2. Removed orphaned `#rhds_container` style.
Closes #1829 
1. View deploy preview.  Note also view Alert's usage of `rh-button` there should be a margin now between the buttons
> fix(button): host display contents

- .changeset/happy-eels-fail.md
- elements/rh-navigation-secondary/rh-navigation-secondary.css
1. Corrected block-end border visibility on dark variant
Closes #1831 
1. [View Deploy Preview](https://deploy-preview-1833--red-hat-design-system.netlify.app/elements/navigation-secondary/demo/dark-variant/)
> fix(navigation secondary):dark variant block-end border visibility

- package-lock.json
- package.json
- tsconfig.json
1. remove `@patternfly/pfe-tools/typescript/transformers/css-imports.cjs`
2. add `typescript-transform-lit-css`
1. make some nested css in a shadow style
2. build clean
3. ensure that *all* the file css is legit in the output
> chore: lit css nesting

- .changeset/sour-cloths-poke.md
- elements/rh-site-status/rh-site-status.css
- elements/rh-site-status/rh-site-status.ts
Closes #1615
1. replace svg with rh-icon in site-status
2. use new status color tokens
3. bodge up a solution to two-tone icons by superimposing the filled icons on the non-filled
> fix(site-status): use rh-icon

- docs/_plugins/shortcodes.cjs
- docs/_plugins/shortcodes/renderLightDom.cjs
- elements/rh-audio-player/docs/40-code.md
- elements/rh-breadcrumb/docs/30-code.md
- elements/rh-code-block/docs/40-code.md
- elements/rh-cta/docs/30-code.md
- elements/rh-footer/docs/30-code.md
- elements/rh-navigation-secondary/docs/30-code.md
- elements/rh-pagination/docs/30-code.md
- elements/rh-skip-link/docs/30-code.md
- elements/rh-subnav/docs/30-code.md
- elements/rh-table/docs/30-code.md
- elements/rh-tile/docs/30-code.md
1. Added a `renderLightDom` shortcode for rendering installation instructions for `Lightdom CSS` 
1. Check the section shows up where necessary, like `skip-link` and `rh-cta` have a lightdom shim, while `footer`, `tile`, and `audio-player` have the proper light dom CSS.
> docs: lightdomcss install shortcode

- .changeset/great-adults-hear.md
- elements/rh-badge/rh-badge.css
- elements/rh-code-block/demo/callout-badges.html
- elements/rh-code-block/demo/prerendered-prism-highlighting.html
- elements/rh-code-block/prism.css.ts
- elements/rh-code-block/prism.ts
- elements/rh-code-block/rh-code-block.css
- elements/rh-code-block/rh-code-block.ts
1. add server-prerendered prism highlighting (i.e. slotted pre.language-foo)
2. remove padding of callout badges
3. fix client-side line numbers.
> feat(code-block): prism prerendered highlighting

- docs/_plugins/rhds.cjs
1. Fixes the element descriptions on overview pages.
Closes #1919 
1. View Deploy preview, you should now see a description of the element below Overview for every element.
> docs: fix getElementDescription filter

- .changeset/six-toys-learn.md
- elements/rh-tabs/rh-tab-panel.css
- elements/rh-tabs/rh-tab-panel.ts
1. Added display contents to panel container (Enables @eyevana's noted issue of subgrid participation)
2. Removed unnecessary lit/context given shift to set panel padding via css var in `rh-tabs.css`
1. [View Deploy preview](https://deploy-preview-1918--red-hat-design-system.netlify.app/elements/tabs/demo/color-context/)
~~@bennypowers don't believe this change needs a changeset as it doesn't change anything for the end user.  Thoughts?~~
> fix(tabs): add display contents to panel container

- docs/assets/javascript/elements/uxdot-repo-status-list.css
1. Corrected border style for `uxdot-repo-status-list` 
1. View deploy preview `uxdot-repo-status-list`  should have a subtle border on inner container.
> docs: `uxdot-repo-status-list` missing border

- .changeset/shaggy-foxes-smoke.md
- elements/rh-tile/rh-tile.css
1. Removed `display: block` on image slot
Closes #1927 
1.  [View Deploy Preview](https://deploy-preview-1928--red-hat-design-system.netlify.app/about/roadmap/) Roadmap tile
2. [View Deploy Preview](https://deploy-preview-1928--red-hat-design-system.netlify.app/elements/tile/demos/) tile demos
3. Look at other implementations of `<rh-tile>`
I'm thinking this change is ok, unsure if it will have negative effects on current usage.  If anything we are correcting an bug but could have layout changing properties if someone had previously tried to slot a non block element into the `image` slot.
> fix(tile): remove `display: block` on image slot

- docs/foundations/color/index.md
1. Changed the max number of columns for the color token swatches from 4 to 3.
1. Check ["Color tokens" section](https://deploy-preview-1901--red-hat-design-system.netlify.app/foundations/color/#color-tokens) of the "Color" page in the DP.
> docs(color): change minimum column width of color token swatches

- docs/assets/javascript/elements/uxdot-sidenav.ts
1. Removed the `role="menu"` and `role="menuitem"` attributes from the `<uxdot-sidenav>` elements.
1. Generally, these roles are not meant for site navigations. See the APG Guidelines for [Menu and Menubar](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/) and MDN docs on the [menu role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role). 
1. aXe DevTools throws an error saying `menu`/`menuitem` have improper nesting
1. Open the [docs DP](https://deploy-preview-1939--red-hat-design-system.netlify.app/), run aXe DevTools, make sure there are no `menu`/`menuitem` errors.
2. Verify `<uxdot-sidenav>` and its child components don't have these roles in the DOM.
> docs: remove `role` attributes from `<uxdot-sidenav>`

- .changeset/gentle-rings-scream.md
- .changeset/large-geese-suffer.md
1. Adjusted language in changesets around tabs and table `@container` support
1.
> docs: adjust changesets to align language around container query support

- elements/rh-card/rh-card.ts
1. Compute context.  First check if `this.colorPalette` is set, if so use that as basis for `light|dark` if undefined check to see if `this.on` is set, if so use that as basis, if not default to light.
1. [View Deploy preview](https://deploy-preview-1943--red-hat-design-system.netlify.app)
Ensure color-context and card patterns function as expected.
> fix(card): computed context

- docs/release-notes/index.md
1. Fixed `<rh-table>`'s on the Release Notes page so that the text inside each `<th>`/`<td>` is visible.
1. Changed some page styles targeting `<rh-table>` to use `@container` queries.
1. Removed `font-weight: 700;` from tile since it's being overridden from component styles.
1. Open up the [Release Notes page](https://ux.redhat.com/release-notes/#changelog) on uxdot in production.
2. Resize window to 770-800px (ish).
3. Observe clipped / hidden text in `<rh-tag>`.
4. Raise one eyebrow.
5. Open up the [Release Notes page](https://deploy-preview-1952--red-hat-design-system.netlify.app/release-notes/#changelog) in this PR's DP.
6. Verify no text is clipped at ~770-800px and everything looks as it should.
7. Lower aforementioned eyebrow.
Closes #1951.
> docs: fix hidden overflow on release notes table

- docs/accessibility/accessibility-tools.md
- docs/accessibility/assistive-tech.md
- docs/accessibility/ci-cd.md
- docs/accessibility/content.md
- docs/accessibility/contributors.md
- docs/accessibility/design.md
- docs/accessibility/development.md
- docs/accessibility/index.md
- docs/accessibility/manual-testing.md
- docs/accessibility/resources.md
- docs/accessibility/screen-readers-computer.md
- docs/accessibility/screen-readers-mobile.md
- docs/accessibility/screen-readers.md
1. Split the screen reader section into three pages
2. Reorganized the a11y sidenav items
3. Cleaned up some typos in the a11y section
1. Go to the main [screen reader page in the DP](https://deploy-preview-1954--red-hat-design-system.netlify.app/accessibility/screen-readers/).
2. Check the tile links in the "Computer screen reader" and "Mobile screen reader" sections and ensure they point to the appropriate page and heading.
1. Go to [any page in the DP](https://deploy-preview-1954--red-hat-design-system.netlify.app/accessibility/screen-readers/).
2. Check the sidenav and ensure all pages in the "Accessibility" section are listed alphabetically.
> docs: accessibility IA and content cleanup

- docs/foundations/color/usage.md
- elements/rh-tag/docs/20-guidelines.md
1. Updated the Foundation status color usage table — organizing the statuses by severity and adding some color for visual reference.
2. Updated Tag's status color guidelines with a link to the foundations.
1. Check everything looks good.
I debated updating Badge and Alerts with a similar link to the foundations section, but those elements seemed to have more in-depth, component-specific color usage guidance than Tag.
> docs: updating status color usage info

- .changeset/nasty-wolves-bake.md
- elements/rh-code-block/docs/30-code.md
- elements/rh-code-block/rh-code-block.ts
1. Fix Prism syntax highlighting for client and prerendered demos of Code Block
2. Fixed an [empty `<code>` tag](https://github.com/user-attachments/assets/7c9ec5d0-8e2f-4736-822f-e135a816ebc8) on the Code sub page of Code Block's docs.
1. Open the following demos:
* [Client Side Highlighting](https://deploy-preview-1973--red-hat-design-system.netlify.app/elements/code-block/demo/client-side-highlighting/)
* [Prerendered Prism Highlighting](https://deploy-preview-1973--red-hat-design-system.netlify.app/elements/code-block/demo/prerendered-prism-highlighting/)
1. Verify syntax highlighting works
1. Compare to demos on `main`:
* [Client Side Highlighting](https://ux.redhat.com/elements/code-block/demo/client-side-highlighting/)
* [Prerendered Prism …
> fix(code-block): prism client and prerendered syntax highlighting

- docs/index.njk
- docs/styles/pages/home.css
1. Put the images in the `image` `slot` in Get Started tiles on the Docs Home, so that it looks better.
1. Does it look cool?
> docs(home): fixing get started tiles

- uxdot/uxdot-best-practice.css
- uxdot/uxdot-best-practice.ts
- Changed icons to their fill versions
- Used `--rh-space-md` for gap between icon and text
1. Check any updated "Best practices" section, like [`<rh-health-index>`'s](https://deploy-preview-2034--red-hat-design-system.netlify.app/elements/health-index/guidelines/#best-practices) in the DP
This addresses @coreyvickery's [comment](https://github.com/RedHat-UX/red-hat-design-system/issues/1449#issuecomment-2442352122) in #1449
> docs(uxdot-best-practice): change Do/Don't heading space and icons

- docs/_includes/partials/component/edit-this-page.njk
- docs/tokens/index.md
Rearranging the Tokens docs by moving Token types up and making them `rh-card` elements.
1. Moved up Tokens types above Tokens categories/
2. Made each type's `<div>` an `<rh-card>` instead and arranged in columns.
> docs(tokens): Rearranging the Tokens docs

- docs/patterns/card/guidelines.md
- elements/rh-card/docs/20-guidelines.md
1. whitespace changes, markdown tables, alt before src in docs sources
2. revise card guidelines to allow non-flush rows
See commit be3f1853a745a1c38a239bf7b47687b879480ec9 for the relevant non-whitespace changes
> docs(card): allow non-flush rows

- .changeset/thick-flowers-beam.md
- elements/rh-blockquote/docs/00-overview.md
- elements/rh-blockquote/docs/10-style.md
- elements/rh-blockquote/docs/20-guidelines.md
- elements/rh-blockquote/docs/40-accessibility.md
- elements/rh-blockquote/rh-blockquote.css
1. Center quotes when using `align="center"`
* Uses `::slotted(p)` to override any `max-inline-size`/`max-width` declarations in end user stylesheets.
1. Enforces a max width of 752px.
1. Update blockquote docs
1. Fixes font size for quote content (bigger!)
1. View the [Centered Demo](https://deploy-preview-2112--red-hat-design-system.netlify.app/elements/blockquote/demo/centered/) in the DP.
3. Ensure the quote is centered.
4. Put in a much longer quote to see how it wraps (at 752px).
5. Make sure other `rh-blockquote` demos look A-OK.
6. Make sure the docs look good.
~~Users are encouraged to handle the line length of their `rh-blockquote`'s themselves (likely by wrapping this in a `<div>` with a `max-width`). This component doesn't specify `max-width`'s.~~
More changes in this PR than …
> fix(blockquote): fix center alignment, enforce blockquote font size and update Style docs

- .changeset/warm-forks-switch.md
- elements/rh-avatar/rh-avatar.css
1.  Removed rule that added bottom margin to `plain` variant avatars
Closes #2149 
1. View Deploy Preview
This may cause the implementation to update their own CSS if they encountered this issue and removed the margin themselves.
> fix(avatar): remove margin-block-end for `plain` variant mobile viewports

- .changeset/forty-colts-tie.md
- elements/rh-footer/demo/slotted-social-links.html
- elements/rh-footer/rh-footer-social-link.css
- elements/rh-footer/rh-footer-social-link.ts
1. allow users to specify a social link in the footer by adding an href attribute to the social link custom element, instead of slotted in a link element.
2. Analytics attributes on the host _should_ still work, so long as the latest click-to-eddl is loaded 🤞 
3. users must also include an `accessible-label` attribute
4. existing markup will still work
5. Even when using the slotted links, JavaScript is still necessary. (see the `updated` method in rh-footer-social link)
1. see the modified rh-footer main demo
2. see the old rh-footer demo, now renamed to slotted social links
> feat(footer): href attribute for social links

- .changeset/moody-ears-clean.md
- elements/rh-card/rh-card.css
Changed the margin-block value of the rh-card `#body` to --rh-space-xl in smaller containers."
Resolved: https://github.com/RedHat-UX/red-hat-design-system/issues/2207
Verify the margin-block value in smaller containers
> fix(card): use `--rh-space` tokens

- elements/rh-footer/rh-footer-social-link.ts
1. Added a description for the `<rh-footer-social-link>` default slot
1. View the [Code docs](https://deploy-preview-2224--red-hat-design-system.netlify.app/elements/footer/code/#rh-footer-social-link-apis) for rh-footer
2. Scroll down to `<rh-footer-social-link>` (or click the link above)
3. Verify the description makes sense / looks good.
Closes #2181
> docs(footer): add default slot description for `<rh-footer-social-link>`

- docs/_includes/layouts/pages/element.11ty.ts
Hopefully this will solve intermittent errors when generating the import map for element pages
> docs: destroy import map cache on error

- docs/_includes/layouts/pages/element.11ty.ts
1. Changed Element heading levels to `<h2>` on Code pages so they show up in the TOC
1. Checkout any Element's Code page in the Deploy Preview, and see its Element docs (Slots, Attributes, etc) listed in the TOC.
This is a temporary "improvement" until we get TOC nesting done.
> docs: make sure primary tag name appears in code page toc

- docs/get-started/designers.md
- docs/get-started/developers/contributing.md
- docs/get-started/developers/index.md
- docs/get-started/developers/installation.md
- docs/get-started/developers/tokens.md
- docs/get-started/developers/usage.md
1. Updated the `href="get-started/..."` links to `href="/get-started/..."` (added the prepending slash) at the bottom the Designer and Developer Get started pages.
1. Click the "go to the Developers/Designers page" links at the bottom of each of the following pages.
2. Ensure they point to the correct destination, and not a 404 page.
- [/get-started/designers/](https://deploy-preview-2247--red-hat-design-system.netlify.app/get-started/designers/) (links to developers page)
- [/get-started/developers/](https://deploy-preview-2247--red-hat-design-system.netlify.app/get-started/developers/) (links to designers page)
- [/get-started/developers/installation/](https://deploy-preview-2247--red-hat-design-system.netlify.app/get-started/developers/installation/) (links to designers page)
- …
> docs: fix get started dev/design cross-link 404s

- elements/rh-card/docs/00-overview.md
- elements/rh-card/docs/20-guidelines.md
- elements/rh-tile/docs/00-overview.md
- elements/rh-tile/docs/20-guidelines.md
1. Added some cards vs tiles content to explain the difference between each
1. Check out Tile's ["When to use"](https://deploy-preview-2245--red-hat-design-system.netlify.app/elements/tile/#when-to-use) section and ["Usage"](https://deploy-preview-2245--red-hat-design-system.netlify.app/elements/tile/guidelines/#usage) guidelines section
2. Check out Card's ["When to use"](https://deploy-preview-2245--red-hat-design-system.netlify.app/elements/card/#when-to-use) section and ["Usage"](https://deploy-preview-2245--red-hat-design-system.netlify.app/elements/card/guidelines/#usage) guidelines section
Closes: #2113
> docs(cards+tiles): adding cards vs tiles context and cross links

- docs/styles/pages/code.css
1. Removed the background color from `<rh-table>` elements inside `<rh-accordion>` on the Elements' Code page.
1. Go to an Element's Code page (like Accordion), scroll down to its slots/properties section, and see if the colors look right.
Closes #2250
> docs(elements-code): fixing accordion + table background colors

- elements/rh-chip/docs/10-style.md
- elements/rh-chip/docs/20-guidelines.md
Made the following edits via feedback from Corey:
- `Style` page
- Under the `Space` heading, apply `<code>` to `--rh-space-lg`
- Under the `Hover` heading, apply `<code>` to `--rh-border-width-md` and `--rh-border-width-sm`
- Under the `Focus and Active` heading, both images look small, so I think removing `width="712"` will display them in the correct size
- `Guidelines` page
- Under the `Chip vs. Badge vs. Tag` heading, in the table, make the `Element` column 25% width and the `Use cases` column 75% width
- Change `Use Cases` to `Use cases`
- Under the `Character count` heading, in the table, make both `Element` and `Character` count columns 50% width
- Change the `Best Practices` heading to `Best practices`
1. Visit the [Style](https://deploy-preview-2260--red-hat-design-system.netlify …
> docs(chip): improve consistency and formatting

- docs/foundations/color/usage/index.md
1. Added content under Foundations > Color > Usage about using black.
1. Checkout the new "Use of black" section, and make sure it reads well.
Closes https://github.com/RedHat-UX/red-hat-design-system/issues/2208
> docs(foundations): adding usage of black color content

- .changeset/eleven-ways-beg.md
- elements/rh-tile/rh-tile-lightdom.css
1. Fixed non-JS issue where the `::after` pseudo-element stretches across the whole page
1. View the [`<rh-tile>` demo](https://deploy-preview-2277--red-hat-design-system.netlify.app/elements/tile/demo/accented-tiles/) and the [homepage of the DP](https://deploy-preview-2277--red-hat-design-system.netlify.app/)
2. Disable JavaScript
3. Compare with [live demo](https://ux.redhat.com/elements/tile/demo/accented-tiles/) and/or the [live homepage](https://ux.redhat.com/) with JS off.
> fix(tile): pre-hydration link `::after` bug

- .changeset/deep-jobs-stay.md
- .changeset/six-trees-train.md
- elements/rh-cta/rh-cta.ts
- lib/themable.ts
1. replace `getUpdateComplete` calls with `scheduleUpdate` calls in cta and `@themable`
1. run dev server, open cta demo
2. observe that arrow appears
`getUpdateComplete()` is only called when actually accessing `el.updateComplete`, and that doesn't happen during the normal lifecycle. therefore we override `scheduleUpdate` instead
> fix: always load dependencies when updating

- docs/release-notes/index.md
1. Fixed a few typos and replaced "colour" with "color."
1. Go to the [DP release notes page](https://deploy-preview-2288--red-hat-design-system.netlify.app/release-notes/)
2. Do a command-f on all of the following and ensure you have no matches:
- naivgation
- degredation
- colour
- destaurated
- cumstomize
> docs: cleaned up release notes typos

- uxdot/uxdot-demo.css
1. Removed the double border between the Demos' `rh-code-block` and `rh-card`
1. Check demos "playground" in the DP
2. Compare to the live version
> docs(demos): removing double border inside demo card + code-block

- .changeset/wise-bears-listen.md
- elements/rh-pagination/rh-pagination-lightdom.css
1. As of Cubone, the ellipsis on the many pages demo on dark color schemes is white/light.
2. If you change to a dark scheme, everything else is dark while the ellipsis is white.
3. This PR makes the ellipsis's background transparent—thus, using the background color of the page/surface behind it.
Before:
After:
1. Open the [Pagination Demo page](https://deploy-preview-2301--red-hat-design-system.netlify.app/elements/pagination/demos/#demo-many-pages) of the docs in the DP.
2. Change to a dark color scheme.
3. Scroll down to the "Many pages" pagination demo (if you're not already there).
4. Verify the ellipsis in the middle of the Many Pages demo has the correct background color (aka none at all).
5. Verify this change works in the full page demos too.
> fix(pagination): fix dark color scheme truncation ellipsis background color

- .changeset/thirty-ends-greet.md
- elements/rh-dialog/rh-dialog.css
1. Always make the close button / icon for video dialogs be white, especially on dark color schemes
Before:
After:
1. View the [video dialog](https://deploy-preview-2303--red-hat-design-system.netlify.app/elements/dialog/demo/video-modal/) in the DP
2. Change the `<main>` element to a `<rh-surface color-palette="darkest">` via DevTools inspector.
3. Open the dialogs.
4. Verify the icon is white / visible against the black background.
5. Refresh the page and verify this also works on light color schemes.
End users have the ability to change the color of their close button/icon via the `--rh-dialog-close-button-color` public variable, should they need to.
> fix(dialog): make video dialog close buttons white

- docs/foundations/typography/scale-and-rhythm/index.md
1. Adds "Small headings" section to "Typography" page.
1. Check DP
Closes #2322
> docs(typography): add table for small headings at desktop size

- .changeset/eighty-results-bow.md
- elements/rh-tabs/demo/icons-and-text.html
- elements/rh-tabs/rh-tab.css
- elements/rh-tabs/rh-tab.ts
1. Corrected hidden icons on tabs. 
2. Removed SlotController
1. View the[ icons demo](https://deploy-preview-2332--red-hat-design-system.netlify.app/elements/tabs/demo/icons-and-text/)
This is likely a SlotController issue but in review of the code I just didn't feel great about the modification of the display rule on slot and by removing that and moving the margin from the icon to the gap rule on the button flex already gets the same effect if a icon is slotted or not.
> fix(tabs): corrected hidden icons

- docs/accessibility/content.md
- docs/accessibility/design.md
- docs/foundations/interactions/links/index.md
1. Expanded the guidance on Interactions in our Accessibility docs, including our [firming up our stance](https://github.com/RedHat-UX/red-hat-design-system/issues/2321) on opening links in new windows
2. Rewording Foundations / Interactions / Links section to match our stance, and cross-linked.
3. Added a link to our stance under our Writing links best practices section in Accessibility
1. Proofread the [User Control](https://deploy-preview-2333--red-hat-design-system.netlify.app/accessibility/design/#user-control) and [Links](https://deploy-preview-2333--red-hat-design-system.netlify.app/accessibility/design/#links-1) sections under Accessibility / Design / Interactions.
2. Proofread [Foundations / Interactions / Links / Behavior](https://deploy-preview-2333--red-hat-design-system.netlif …
> docs(a11y): adding guidance for opening links in new windows

- .changeset/green-corners-strive.md
- elements/rh-dialog/demo/lots-of-content.html
- elements/rh-dialog/rh-dialog.css
Fixes #2341.
1. Go to the [demo](https://deploy-preview-2342--red-hat-design-system.netlify.app/elements/dialog/demo/) in the DP or locally.
2. Open DevTools.
3. Add lots of content before and after the dialog and dialog trigger.
4. Open the dialog.
5. Ensure the dialog doesn't scroll to the very top of the page upon opening (like it does in this [reduced test case](https://codepen.io/adamjohnson/pen/GggWEaJ)).
6. Test these same things with each `variant` and `position` attribute ([docs](https://ux.redhat.com/elements/dialog/code/#rh-dialog-apis)).
7. Test these same things in the [Lots of Content](https://deploy-preview-2342--red-hat-design-system.netlify.app/elements/dialog/demo/lots-of-content/) demo.
8. Make sure this also works with the [video …
> fix(dialog): prevent dialog from scrolling to the top of the page after hitting dialog's trigger

- .changeset/seven-dragons-jam.md
- elements/rh-dialog/demo/form.html
- elements/rh-dialog/rh-dialog.ts
- elements/rh-dialog/test/rh-dialog.spec.ts
Adding an event listener to the native dialog element to handle if the dialog is cancelled outside of the context of the  element
1.  I added an event listener to the dialog in the `firstUpdated()` function that calls a function called `#onNativeDialogCancel` when the dialog element sends a cancel event.
2. The native dialog cancel prevents the default behavior and instead calls out components `cancel` method directly.
1.  Open the demo site
2. Go to the `Lots of Content` page
3. Open the dialog
4. Tab out of the dialog
5. Click the address bar
6. Tap the `ESC` key twice
7. The scrollbar should be enabled.
> fix(dialog): scrollbar state after closing

- .changeset/short-squids-obey.md
- elements/rh-audio-player/rh-audio-player.css
1. ensure menu button is hidden when transcript is open (chrome)
1. view transcript demo in all three browsers
2. click menu
3. click transcript
4. observe that close button is well positioned and menu button is not visible
Closes #2362
> fix(audio-player): close button (chrome)

- .changeset/shaky-things-melt.md
- elements/rh-audio-player/rh-audio-player.css
1. align the play icon in webkit
1. Please see attached issue
2. https://deploy-preview-2373--red-hat-design-system.netlify.app/elements/audio-player/demo/
3. Before: <img width="949" alt="Screenshot 2025-05-14 at 10 51 53" src="https://github.com/user-attachments/assets/78505c9e-8154-42a6-a40a-7f7f7f1551c4" />
4. After: <img width="910" alt="Screenshot 2025-05-14 at 13 28 47" src="https://github.com/user-attachments/assets/2135ea8d-5c9b-47b0-96cf-1be42b228dea" />
Closes #2372
> fix(audio-player): play icon misalignment webkit

- docs/_includes/layouts/pages/element.11ty.ts
Closes #2346 
1. remove uncouth backticks from demos page codeblocks. so rude.
1. https://deploy-preview-2374--red-hat-design-system.netlify.app/elements/tag/demos/
2. check out a demo html codeblock, scroll to the bottom
> docs: demo codeblock backticks

- .changeset/lemon-owls-peel.md
- elements/rh-breadcrumb/demo/truncate.html
- elements/rh-breadcrumb/rh-breadcrumb-lightdom.css
- elements/rh-breadcrumb/rh-breadcrumb.ts
- elements/rh-breadcrumb/test/rh-breadcrumb.spec.ts
1. Added a prop, `truncate`, to allow middle breadcrumb items to be temporarily replaced by a button.
2. Users can click the button to 1) show the middle breadcrumb buttons and 2) remove the button from the DOM.
1. Requires the `truncate` boolean property
2. Only truncates when there are more than four breadcrumb items
3. Starts truncation at the second list item
4. Ends truncation at the third to last list item
1. View the [DP demo](https://deploy-preview-2357--red-hat-design-system.netlify.app/elements/breadcrumb/demo/truncate/).
1. Ensure I am taking the right approach in the code.
Based off of [this Figma](https://www.figma.com/proto/FSkPCjWTWK63QfSnX8rChZ/rh-breadcrumb?page-id=1%3A3&type=design&node-id=1-218&viewport=122%2C139%2C1&t=AmmdkOlWBdRh2fWu-1&scaling=min-zoom).
We can …
> feat(breadcrumb): add truncation

- .changeset/cruel-walls-carry.md
- elements/rh-code-block/rh-code-block.ts
1. load the prerendered styles from a module which doesn't also load prism
1. check out some prerendered codeblocks in the dp, make sure they work.
2. Find a page that *only* has prerendered code blocks - reload with network panel open, ensure prism-esm.js is not loaded
3. find a page with both preloaded and client code blocks, they should work
This should help with code block perf on large docs pages
cc @kylebuch8
> perf(code-block): avoid loading prism when prerendered

- .changeset/thin-baboons-do.md
- elements/rh-code-block/demo/actions.html
- elements/rh-code-block/rh-code-block.ts
Closes #2121
1. lazy load tooltip client side when actions are used
1. load the actions demo, tooltips should work
> fix(code-block): autoload tooltip for fabs

- .changeset/stale-pans-throw.md
- elements/rh-tooltip/rh-tooltip.css
- elements/rh-tooltip/rh-tooltip.ts
1. compute the contrasting "color-scheme" value for tooltips when they open
1. pick a page with tooltips, maybe in a demo or a code block, preferably with themable content like `<code>`
2. toggle color schemes back and forth
3. open the tooltip and observe that the themable content is legible
This came up when working on knobs #2379.
This all happens in the `open()` method, so it should be client-side only and not cause ssr mismatches.
also NB that we neglected to delete the deprecated properties when releasing cubone, so we should prioritize that for the next breaking change, whenever that might be
> fix(tooltip): contrasting color-scheme

- .changeset/modern-humans-nail.md
- elements/rh-navigation-primary/rh-navigation-primary-item.css
- elements/rh-navigation-primary/rh-navigation-primary.css
1. Corrected `:active` state for hamburger menu and secondary slotted nav items
1. [View Deploy preview](https://deploy-preview-2394--red-hat-design-system.netlify.app/elements/navigation-primary/demo/) on `:active` you should no longer get a outline ring like you do on `:focus`
> fix(navigation-primary): correct active states

- .changeset/thick-wings-live.md
- elements/rh-subnav/rh-subnav.ts
This occurs when esbuilding the library e.g. for the 11ty dev server
1. avoid querying dom when it's not ready.
1. `npm run serve` - go to a page with a subnav, there should be no errors in the dev console
> fix(subnav): prevent early dom access error

- docs/styles/styles.css
- uxdot/uxdot-feedback.css
- uxdot/uxdot-feedback.ts
- uxdot/uxdot-masthead.css
1. Added the dashed underline for inline links in docs
1.  Make sure that the underline styles for inline links on ux dot match the inline link styles on our Interactions > [Links page](https://ux.redhat.com/foundations/interactions/links/#interaction-states)
> docs: add new dashed underline style to inline links

- .changeset/wet-papayas-bow.md
- elements/rh-badge/rh-badge.css
- elements/rh-badge/rh-badge.ts
Closes #2397 
1. add a slot to rh-badge
2. hide the slot when there's a number attribute
3. hide the span otherwise
1. see codeblock demos - badges should appear
This adds a downstream footgun. previously, if a developer did this:
```html
<rh-badge><span class="big-and-ugly">AHHA</span></rh-badge>
```
Then the badge would render the text "AHHA" without styles. Now, it will render it big & ugly
> fix(badge): ssr hydration mismatch

- .changeset/odd-paws-wonder.md
- elements/rh-code-block/demo/callout-prerendered.html
- elements/rh-code-block/rh-code-block.ts
1. add a demo for code-block illustrating how to add rh-badge callouts for prerendered code
2. fix the private copy method to work with such code blocks
1. use the copy button on [the new demo](https://deploy-preview-2391--red-hat-design-system.netlify.app/elements/code-block/demo/callout-prerendered/), ensure copied result is correct
> fix(code-block): prerendered callouts

- docs/styles/styles.css
1. Added a recognizable background color to `<code>` elements that exist on dark color schemes.
1. Visit the DP.
2. Turn on the dark color scheme.
3. Go to any page with `<code>` tags.
* [Theming > Developers](https://deploy-preview-2402--red-hat-design-system.netlify.app/theming/developers/)
* Any Elements > Code page, eg [Dialog](https://deploy-preview-2402--red-hat-design-system.netlify.app/elements/dialog/code/#rh-dialog-apis)
* Any [Tokens](https://deploy-preview-2402--red-hat-design-system.netlify.app/tokens/color/) page.
Closes #2393.
> docs: improve `<code>` element rendering on dark color schemes

- elements/rh-accordion/docs/40-accessibility.md
1. Removed extraneous `>` from below the Touch Targets graphic on the accessibility page
1. Go to the live version of the Touch Targets section on Accordion's Accessibility page
2. See extraneous `>` below graphic
3. Compare to the DP's version
> docs(accordion): removing extraneous > from accessibility page

- docs/release-notes/index.md
1. Added v3.0.4 to the Release Notes page.
1. View [the DP](https://deploy-preview-2458--red-hat-design-system.netlify.app/release-notes/).
2. Check that it matches what's listed on [Github](https://github.com/RedHat-UX/red-hat-design-system/releases/tag/v3.0.4).
Please review and approve https://github.com/RedHat-UX/red-hat-design-system/pull/2434 before approving this PR.
> docs(release-notes): add v3.0.4 notes

- docs/_includes/layouts/pages/element.11ty.ts
1. If you look at any Code page on uxdot that has custom content coming from a `30-code.md` file (eg: [Spinner](https://ux.redhat.com/elements/spinner/code/)), you'll notice that content is duplicated on the page.
2. This PR fixes that.
1. View the existing duplicated content on uxdot element Code pages like rh-icon, rh-alert, rh-table, rh-spinner, rh-code-block, rh-pagination, rh-navigation-secondary and maybe others.
2. View the Code page for those elements in [this DP](https://deploy-preview-2485--red-hat-design-system.netlify.app/elements/spinner/code/) and verify the content is not duplicated.
3. Verify that instructions for lightdom and lightdom shim CSS still work on these elements and for other elements that don't have custom content in `30-code.md`.
> docs(code): fix duplicate rendering of `30-code.md` content

- .changeset/funny-badgers-burn.md
- elements/rh-alert/rh-alert.ts
- elements/rh-alert/test/rh-alert.spec.ts
Closes #2478
1. ensure the computed state is always lowercase
2. add unit tests
1. https://deploy-preview-2484--red-hat-design-system.netlify.app/elements/alert/
2. Inspect the rh-alert in the demo (don't use the knobs, use the dev tools)
3. set the state attribute value to `neUtRal`.
4. observe grey (not teal!) background color
> fix(alert): case insensitive state

- uxdot/uxdot-sidenav.css
- uxdot/uxdot-sidenav.ts
1. Adds a `<h2>` with `aria-labelledby` to the main navigation on ux.redhat.com.
2. Closes #2579. 
1. Open up the homepage of uxdot on [this PR's DP](https://deploy-preview-2581--red-hat-design-system.netlify.app/).
2. Right click and inspect "Home" in the `<uxdot-sidenav>`.
3. View the new `<h2>` that provides a label for the `<nav>` element in that component's shadowroot.
4. Ensure the ID and the `aria-labelledby` attribute match.
5. Ensure the `<h2>` is visually hidden.
6. Test with various a11y technology (Lumar, axe, screen readers, et all) to make sure these changes don't flag any new warnings or errors).
> fix(uxdot-sidenav): add `<h2>` to uxdot's main side navigation

- .changeset/orange-bats-serve.md
- elements/rh-pagination/rh-pagination.css
1. This PR defines `--rh-color-icon-status-disabled` in `rh-pagination.css` and uses it for the disabled stepper (left and right arrow) icons.
2. Closes #2516. 
1. View the [Color Context demo](https://deploy-preview-2596--red-hat-design-system.netlify.app/elements/pagination/demo/color-context/) in the DP.
2. Verify the disabled stepper icon color looks correct in both light and dark color schemes. 
According to @coreyvickery's [comment](https://github.com/RedHat-UX/red-hat-design-system/pull/2593#issuecomment-3238070197), this changes the light disabled stepper icon color to `gray-50`.
This seems like a much more _contrasty_ disabled state for light color schemes. Ensure this change is intended.
> fix(pagination): change inactive stepper icon color

- .changeset/famous-gifts-sip.md
- elements/rh-tabs/rh-tab.css
- elements/rh-tabs/rh-tabs.css
1. Changes the dark scheme background color of the box variant of inactive `<rh-tab>` elements.
2.  Closes #2517. 
1. Open the [Box Inset demo](https://deploy-preview-2593--red-hat-design-system.netlify.app/elements/tabs/demo/box-inset/) on the DP.
2. Right click > Inspect Element on an inactive tab.
3. Add `color-palette="darkest"` to the parent `<rh-tabs>` element.
4. Verify the appropriate background color exists for inactive box variant tabs.
5. Verify this change doesn't adversely affect other tab variants.
> fix(tabs): update the background color of inactive box variant tabs

- package-lock.json
- package.json
1. Updated CEM from v0.3.0 to v0.4.6.
1. Pull down the branch, `git clean -fdx && npm ci && npm run serve`.
2. Compare the custom element manifest (.json in root after `serve`) does not have any regressions compared to main. 
3. Check docs, make sure there are no regressions, especially on the Code and Tokens pages.
> chore(cem): update to v0.4.6
